"""The deployed assets carry no home-path-shaped text (DEF-956).

Fourteen comment and docstring lines across three managed modules spelled real
home-directory shapes verbatim, and an adopter who extended a home-path content
scan to Python found the only hits in files they cannot edit: every one is
managed, regenerated by init and upgrade, two of them integrity-hashed. The
literal spellings stay in the test suite and in docs/SHARP_EDGES.md, neither of
which is deployed; a deployed asset writes ``<home>`` or says the shape in words.

This test pins every deployed text asset against a small home-path shape set,
with a per-root floor, because the class regrows silently otherwise: a new
comment that spells a real home prefix ships in the next wheel and is caught by
the next adopter's scanner rather than here.
"""
from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEPLOYED_ROOTS = ("espalier/_vendor/cc", "espalier/assets")
TEXT_SUFFIXES = {".py", ".md", ".js", ".json", ".toml", ".txt", ".yml", ".yaml", ".cmd", ".ps1"}
HOME_SHAPES = re.compile(
    r"/Users/[A-Za-z.]"            # a macOS home prefix with a user segment
    r"|/home/[A-Za-z]"             # a Linux home prefix with a user segment
    r"|[\\/]Users[\\/]"            # a Windows profile path, whatever precedes it (`C:\`, `C:\c\`)
    r"|/[a-z]/Users/"              # the MSYS drive form of one
    r"|USERPROFILE%?[\\/]"         # the profile variable spliced into a path (the bare name is a mention)
    r"|-Users-[A-Za-z]"            # the per-character project-directory encoding of one
)


def _deployed_text_files():
    for root in DEPLOYED_ROOTS:
        for path in sorted((REPO_ROOT / root).rglob("*")):
            if path.is_file() and path.suffix in TEXT_SUFFIXES and "__pycache__" not in path.parts:
                yield path


class TestDeployedAssetsCarryNoHomePathShape:
    def test_no_deployed_file_spells_a_home_path(self):
        hits = []
        for path in _deployed_text_files():
            text = path.read_text(encoding="utf-8", errors="replace")
            for n, line in enumerate(text.splitlines(), 1):
                if HOME_SHAPES.search(line):
                    hits.append(f"{path.relative_to(REPO_ROOT).as_posix()}:{n}: {line.strip()[:100]}")
        assert not hits, "home-path-shaped text in deployed assets:\n  " + "\n  ".join(hits)

    def test_the_rule_set_sees_each_shape_and_not_the_tokens(self):
        for sample in ("/Users/x/repo", "/home/me/repo", "/home/Mike/repo", "C:\\Users\\me", "C:/Users/me",
                       "/c/Users/me", "C:\\c\\Users\\x", "USERPROFILE\\repo", "%USERPROFILE%/x", "-Users-x-Repo"):
            assert HOME_SHAPES.search(sample), sample
        # The bare variable name is a legitimate mention of the variable, not a path.
        for inert in ("<home>/repo", "/c/<home>/x", "C:\\<home>", "C:\\c\\<home>\\x", "/srv/x/Repo",
                      "~/.claude/projects", "USERPROFILE", "$env:USERPROFILE", "the USERPROFILE value"):
            assert not HOME_SHAPES.search(inert), inert

    def test_the_scan_read_each_deployed_root(self):
        """A missing root makes `rglob` silent; a global floor would let one
        root's count carry a dead one (the failure-mode review drove it).
        Each root exists and holds a floor of its own."""
        for root in DEPLOYED_ROOTS:
            directory = REPO_ROOT / root
            assert directory.is_dir(), root
            count = sum(1 for p in directory.rglob("*") if p.is_file() and p.suffix in TEXT_SUFFIXES and "__pycache__" not in p.parts)
            assert count > 20, (root, count)
