"""Regression: user-authored `tools/` is not the same as harness `tools/cc/`.

Before TP-RELEASE-06, `espalier/analyze.py` defined
`BUILDER_OUTPUT_PARTS = {".claude", "tools", "reports"}` and matched it as a
basename anywhere in the path. That excluded any directory named `tools/`,
including a consumer repo's legitimate `tools/` containing user scripts.

The fix narrows the exclusion to specific path *prefixes*
(`tools/cc/`, `reports/`, `cc/blueprints/`, `bench/results/`, `.claude/`).
This test fixes that behavior in place: a user file at `tools/user_script.py`
must be analyzed, and only files under `tools/cc/` (Espalier-Harness's own
generated output) must be excluded.
"""
from __future__ import annotations

from pathlib import Path

from espalier.analyze import (
    HARNESS_OUTPUT_PREFIXES,
    _iter_files,
    detect_languages,
    detect_runtime_surface,
)


def _scaffold_user_repo(root: Path) -> None:
    """Build a synthetic consumer repo where `tools/` is mostly user code,
    with a single `tools/cc/` subdirectory representing harness output."""
    (root / "tools").mkdir()
    (root / "tools" / "user_script.py").write_text(
        "def user_function():\n    return 42\n", encoding="utf-8"
    )
    (root / "tools" / "utility").mkdir()
    (root / "tools" / "utility" / "helper.py").write_text(
        "def helper():\n    return 1\n", encoding="utf-8"
    )
    (root / "tools" / "cc").mkdir()
    (root / "tools" / "cc" / "harness_script.py").write_text(
        "# generated by espalier init\n", encoding="utf-8"
    )


def test_user_tools_directory_is_iterated(tmp_path: Path):
    """User-authored `tools/` files survive _iter_files; only `tools/cc/` is filtered."""
    _scaffold_user_repo(tmp_path)
    rels = {
        str(p.relative_to(tmp_path)).replace("\\", "/")
        for p in _iter_files(tmp_path)
    }
    assert "tools/user_script.py" in rels, (
        "User-authored tools/user_script.py was excluded by the analyzer. "
        f"Iterated files: {sorted(rels)}"
    )
    assert "tools/utility/helper.py" in rels, (
        "Nested user tools/utility/helper.py was excluded — the basename match "
        "regression that TP-RELEASE-06 fixes."
    )
    assert "tools/cc/harness_script.py" not in rels, (
        "Generated tools/cc/harness_script.py was included even though "
        "harness output should be excluded from consumer-repo analysis."
    )


def test_user_tools_python_files_count_in_language_detection(tmp_path: Path):
    """detect_languages should count user tools/*.py and skip tools/cc/*.py."""
    _scaffold_user_repo(tmp_path)
    counts, ordered = detect_languages(tmp_path)
    # 2 user Python files (user_script.py + utility/helper.py); harness file excluded.
    assert counts.get("python", 0) == 2, (
        f"Expected 2 user Python files counted, got {counts}. "
        "tools/cc/ should be excluded but tools/ and tools/utility/ should not."
    )


def test_top_level_tools_python_package_is_detected_as_runtime_surface(tmp_path: Path):
    """A user's top-level `tools/` Python package with __init__.py is
    detected by detect_runtime_surface — was suppressed by the old
    basename-set exclusion."""
    (tmp_path / "tools").mkdir()
    (tmp_path / "tools" / "__init__.py").write_text("", encoding="utf-8")
    (tmp_path / "tools" / "main.py").write_text(
        "def main(): pass\n", encoding="utf-8"
    )
    surface = detect_runtime_surface(tmp_path)
    assert "tools" in surface, (
        "User's top-level tools/ Python package was not detected as runtime "
        f"surface. detect_runtime_surface returned: {surface}. "
        "TP-RELEASE-06 narrowed the harness-output skip (is_harness_output today) specifically "
        "so this case stops being silently dropped."
    )


def test_harness_output_prefixes_does_not_contain_bare_tools():
    """Lock the constant shape: `tools` alone must never reappear as a prefix
    (only `tools/cc` is harness output)."""
    assert "tools" not in HARNESS_OUTPUT_PREFIXES, (
        "Bare 'tools' prefix would re-introduce the TP-RELEASE-06 overreach. "
        "Use 'tools/cc' for the Espalier-Harness hook directory only."
    )
    assert "tools/cc" in HARNESS_OUTPUT_PREFIXES, (
        "tools/cc must remain in HARNESS_OUTPUT_PREFIXES — that's Espalier-Harness's "
        "own generated hook output and should not be re-included."
    )
