"""TP-53 source hygiene — git archive parity.

Pins the invariant that generated runtime artifacts never leak
into the source distribution. ``git archive HEAD`` must be a
faithful snapshot of "what git knows about" — nothing more,
nothing less. This guard prevents the "release zip contains files
git wouldn't" class of bug:

- ``.espalier/integrity.json`` (per-checkout, regenerated by
  ``espalier integrity refresh``) used to be tracked and produced
  spurious diffs after every refresh; TP-53 untracked it.
- ``.claude/settings.json`` (per-machine: it records the interpreter
  name detected on PATH) is gitignored — but if it ever drifts into
  the index, this test fires.
- ``reports/*.json`` are per-install fingerprints; same protection.

The test runs ``git archive`` into a temp dir, walks the extracted
tree, and asserts no entry from the gitignored-but-must-stay-
untracked set appears. Without this contract, a stray ``git add``
of one of these files would silently ship adopter-machine secrets
(absolute paths, integrity hashes) inside every source archive
release.
"""
from __future__ import annotations

import subprocess
import tarfile
from pathlib import Path

import pytest

from espalier import surface_contract
from tests._git_oracle import require_head_tree_paths, require_tracked_paths

REPO_ROOT = Path(__file__).resolve().parent.parent

# Non-vacuity floor for whole-tree git populations in this module. Well below the
# live count (>900 tracked) and above any plausible partial checkout, matching the
# `> 500` idiom at `test_release_pack.py::TestWalkPruning`. Stricter per-test floors (e.g.
# `>= 900` in test_surface_contract_matcher_agrees_with_git_on_every_tracked_path)
# stay where they are -- this is the shared minimum, not a replacement for them.
_POPULATION_FLOOR = 500

# Per-install / per-machine generated state that MUST NOT appear in
# ``git archive HEAD``. Each entry is a path relative to the repo root.
# Add a new entry here whenever a new generated artifact joins the
# gitignore + must-not-track set.
MUST_NOT_BE_IN_ARCHIVE: tuple[str, ...] = (
    ".espalier/integrity.json",
    ".espalier/.manifest.write.lock",
    ".claude/settings.json",
    ".claude/settings.local.json",
    "reports/repo_fingerprint.json",
    "reports/harness_config.json",
    "reports/cc_surface_gate.json",
    "cc/blueprints/latest.json",
    "cc/BLUEPRINT_HANDOFF.md",
    "cc/SURFACE_HANDOFF.md",
    "cc/execution_plan.json",
    "docs/session-archive.md",
)
# NOTE: ESPALIER_MEMORY.md / memory/*-atlas.md are TRACKED (kept in-repo
# for transparency) but excluded from `git archive` via .gitattributes
# export-ignore — a different category from the untracked per-install artifacts
# above, so they live in EXPORT_IGNORED_INTERNAL_DOCS (below) and are checked by
# the archive-membership test, NOT the staged-index "must not be tracked" test.


pytestmark = [pytest.mark.contract, pytest.mark.release]


def _git_archive_to_tar(tmp_path: Path, ref: str, *, worktree_attributes: bool = False) -> Path:
    """Produce ``git archive <ref>`` as a tarball in ``tmp_path``.

    ``worktree_attributes=True`` adds ``--worktree-attributes`` so the archive
    honours the working-tree ``.gitattributes`` rather than the committed one —
    used to validate export-ignore rules before the ``.gitattributes`` commit
    lands (TP-171 §3.1).
    """
    tar_path = tmp_path / f"{ref.replace('/', '_')}.tar"
    cmd = ["git", "archive", "--format=tar"]
    if worktree_attributes:
        cmd.append("--worktree-attributes")
    cmd.append(ref)
    result = subprocess.run(
        cmd,
        cwd=str(REPO_ROOT),
        capture_output=True,
        check=True,
        timeout=60,
    )
    tar_path.write_bytes(result.stdout)
    return tar_path


# TP-171 §3.1: internal harness-dev docs excluded from the public archive.
EXPORT_IGNORED_INTERNAL_DOCS: tuple[str, ...] = (
    "ESPALIER_MEMORY.md",
    "memory/injection-opportunity-atlas.md",
    "memory/generative-injection-atlas.md",
    "memory/speedbump-checkpoint-atlas.md",
    "memory/publish-from-a-generated-public-repo.md",
    # TP-184 B8: tracked internal contract-shorthand (TP/BC dev vocabulary, zero
    # adopter value). MANIFEST.in already excludes it from the sdist, but it is
    # TRACKED (unlike the untracked session-archive.md), so it shipped in
    # `git archive` (GitHub "Download ZIP") and the bespoke release zip until the
    # .gitattributes export-ignore line + the classify_release_path='internal'
    # reclassification closed both vectors.
    "docs/REDEFINED_INFORMATION_REGISTRY.md",
    # Release-engineering provenance (finding->commit ledger for TP-156..184).
    # TRACKED for transparency but internal historical narrative; classified
    # 'internal' + MANIFEST-excluded + export-ignored, same footprint as
    # REDEFINED above.
    "docs/RELEASE_FINDINGS_LEDGER.md",
    # NOT here since 2026-09-21: task-packs/CLAUDE.md. The router ships with the
    # forward ledger and the active packs; the export-ignore rows under
    # /task-packs/ now name the landed / merged / scrapped subtrees and the dated
    # archive families, none of which is a plain-file entry.
    # The two release-engineering docs (2026-08-13). Maintainer ritual naming the
    # operator's own accounts and the one-time pre-flip sequence; TRACKED for
    # transparency, classified 'internal' + MANIFEST-excluded + export-ignored,
    # same footprint as the ledger above. Unlike the four docs above these were
    # LINKED from docs/README.md, so the reclassification also had to convert
    # those two index rows out of markdown-link form -- an export-ignored link
    # target reds both dangling-link gates (this file and test_wheel_payload.py).
    "docs/RELEASE_CHECKLIST.md",
    "docs/RELEASE_DECISIONS.md",
)


def _archive_members(tar_path: Path) -> set[str]:
    with tarfile.open(tar_path) as tf:
        return {m.name for m in tf.getmembers() if m.isfile()}


def _tracked_paths_at_head() -> set[str]:
    """Return paths in the HEAD commit tree.

    Distinct from :func:`_staged_tracked_paths` (the index) on purpose: this is
    the exact population ``git archive HEAD`` draws from, so a comparison of the
    two is apples-to-apples. Using the index instead would report a staged-but-
    uncommitted add as "pruned by git".

    ``check=True`` made rc 128 loud but left the OTHER empty case silent: inside
    a gitignored directory git answers rc 0 with zero rows, and every consumer
    here does a membership test against a denylist, which an empty set satisfies.
    Measured 2026-08-14 -- `test_unregistered_sentinel_hatch_is_untracked_only`
    went green under `dist/` and red outside it, same archive. §C21/`DEF-569`;
    the floor now lives in one place for all three consumers rather than being
    re-remembered per test (two of the three already had one, which is precisely
    how the third's absence stayed invisible).
    """
    return set(require_head_tree_paths(
        REPO_ROOT, minimum=_POPULATION_FLOOR, what="paths in the HEAD tree"
    ))


def _staged_tracked_paths() -> set[str]:
    """Return paths in the current git index (staged state). Reflects
    the post-commit state once changes are committed; useful for
    pre-commit validation when HEAD is older than the working tree.

    Floored for the same reason as :func:`_tracked_paths_at_head`, and this is
    the higher-consequence of the two: its sole consumer checks the 12-entry
    ``MUST_NOT_BE_IN_ARCHIVE`` denylist -- the gate against a kill-switched
    ``.claude/settings.json`` or an ``.espalier/integrity.json`` reaching the
    index -- and an empty set satisfies that check completely. §C21/`DEF-568`.
    """
    return set(require_tracked_paths(
        REPO_ROOT, minimum=_POPULATION_FLOOR, what="paths in the git index"
    ))


def test_staged_index_excludes_per_install_artifacts():
    """No gitignored runtime artifact may be staged for the next commit.

    This is the pre-commit signal: ``git ls-files`` reflects the index,
    so a leaked artifact shows up here BEFORE the commit lands.
    """
    staged = _staged_tracked_paths()
    leaks = sorted(rel for rel in MUST_NOT_BE_IN_ARCHIVE if rel in staged)
    assert not leaks, (
        "git index has per-install artifacts staged:\n  "
        + "\n  ".join(leaks)
        + "\n\nRemediation: git rm --cached <path> and verify "
        ".gitignore covers it; commit the change."
    )


def test_git_archive_head_excludes_per_install_artifacts(tmp_path):
    """``git archive HEAD`` is the release-shipping state; per-install
    artifacts must not appear there. Lags the index by one commit, so
    a fresh untrack only takes effect after the commit that records it.
    """
    tar_path = _git_archive_to_tar(tmp_path, "HEAD")
    members = _archive_members(tar_path)
    leaks = sorted(rel for rel in MUST_NOT_BE_IN_ARCHIVE if rel in members)
    assert not leaks, (
        "git archive HEAD leaked per-install artifacts:\n  "
        + "\n  ".join(leaks)
        + "\n\nRemediation: git rm --cached <path> and verify "
        ".gitignore covers it; commit the change."
    )


def test_git_archive_export_ignores_internal_docs(tmp_path):
    """TP-171 §3.1: the .gitattributes export-ignore rules keep internal
    harness-dev docs (the unexecuted design proposal, the dev memory log, and
    the inject/bypass atlases) out of `git archive`. Uses --worktree-attributes
    so the contract holds against the working-tree .gitattributes regardless of
    whether it is committed yet (the plain-HEAD test above lags by one commit).
    """
    tar_path = _git_archive_to_tar(tmp_path, "HEAD", worktree_attributes=True)
    members = _archive_members(tar_path)
    leaks = sorted(rel for rel in EXPORT_IGNORED_INTERNAL_DOCS if rel in members)
    assert not leaks, (
        "git archive (worktree-attributes) shipped internal docs that should be "
        "export-ignored:\n  " + "\n  ".join(leaks)
        + "\n\nRemediation: add an `<path> export-ignore` line to .gitattributes."
    )


# Export-ignore entries that need no EXPORT_IGNORED_INTERNAL_DOCS binding, each
# with the reason. A dict, not a set, for the same reason ARTIFACT_LINK_ALLOWLIST
# below is one: "an unexplained exclusion inside a mechanical gate is itself an
# un-tested assertion." Bound by the two meta-tests after the alarm.
UNREGISTERED_EXPORT_IGNORE_SENTINELS: dict[str, str] = {
    "docs/session-archive.md": (
        "UNTRACKED (gitignored) — cannot reach `git archive` regardless of "
        "registration; its export-ignore line marks it intentionally-internal "
        "for the cleanliness gate's parser, not as a binding. Absence is still "
        "asserted twice over, via MUST_NOT_BE_IN_ARCHIVE."
    ),
}


def test_every_plain_file_export_ignore_is_registered():
    """The REVERSE direction, and the one that actually catches sister-site drift.

    Every other assertion here runs ``EXPORT_IGNORED_INTERNAL_DOCS`` -> archive:
    "is each listed doc absent?" That is one-directional, so adding a
    ``.gitattributes`` export-ignore line and forgetting every other sister site
    reds NOTHING. Making a doc internal touches four-to-seven files
    (docs/SHARP_EDGES.md "A tracked internal doc needs a sister-site footprint");
    this binds the cheapest one to the registry so a half-done reclassification
    cannot ship green.

    The two sides are INDEPENDENTLY WRITTEN on purpose — ``.gitattributes`` is
    hand-edited by the person doing the reclassification, this tuple is hand-kept
    here. Deriving one from the other would reproduce the closed-loop trap that
    tests/test_self_hosting.py's fixture documents (§C1 tier 2: a contract needs
    two independent derivations, not one narrowing duplicated).
    """
    plain_files = {
        pat for pat in surface_contract.export_ignore_patterns(REPO_ROOT)
        if not pat.endswith("/") and not any(ch in pat for ch in "*?[")
    }
    assert plain_files, "test setup: .gitattributes yielded no plain-file entries"
    unregistered = sorted(
        plain_files
        - set(EXPORT_IGNORED_INTERNAL_DOCS)
        - set(UNREGISTERED_EXPORT_IGNORE_SENTINELS)
    )
    assert not unregistered, (
        "these .gitattributes export-ignore entries are not registered in "
        f"EXPORT_IGNORED_INTERNAL_DOCS: {unregistered}. An export-ignore line "
        "alone is half a reclassification — walk the sister-site footprint in "
        "docs/SHARP_EDGES.md (classifier, MANIFEST.in, this registry, and the "
        "conditional sites) or add the path to "
        "UNREGISTERED_EXPORT_IGNORE_SENTINELS with the reason it needs no binding."
    )


def test_unregistered_sentinel_hatch_entries_carry_a_reason():
    """Same contract ARTIFACT_LINK_ALLOWLIST carries, for the same reason."""
    blank = sorted(k for k, v in UNREGISTERED_EXPORT_IGNORE_SENTINELS.items()
                   if not v.strip())
    assert not blank, (
        f"these hatch entries silence the export-ignore alarm with no stated "
        f"reason: {blank}"
    )


def test_unregistered_sentinel_hatch_is_untracked_only():
    """The hatch exists for entries that CANNOT reach an archive — i.e. untracked
    ones. A TRACKED path added here would silence the alarm permanently *and*
    drop out of EXPORT_IGNORED_INTERNAL_DOCS, so its archive-absence would be
    asserted by nothing at all. That is the one use of this hatch that turns a
    bookkeeping gap into a real leak, so it is the one the hatch must refuse.
    """
    tracked = _tracked_paths_at_head()
    wrongly_hatched = sorted(
        rel for rel in UNREGISTERED_EXPORT_IGNORE_SENTINELS if rel in tracked
    )
    assert not wrongly_hatched, (
        f"{wrongly_hatched} are TRACKED, so they can reach `git archive` — the "
        "hatch is only for untracked paths whose absence is guaranteed by git. "
        "Register them in EXPORT_IGNORED_INTERNAL_DOCS instead."
    )


def test_no_internal_classified_tracked_file_ships_in_the_archive(tmp_path):
    """The DERIVED complement of the hand-kept alarm above, and the one that
    catches an actual leak rather than a bookkeeping miss.

    Every other assertion here binds one hand-written list to another, so all of
    them share a blind spot: `classify_release_path` — the canon — participates in
    no archive gate at all. `test_wheel_payload::test_sdist_excludes_internal_
    classified_files` derives classify -> sdist; this is its missing `git archive`
    twin. Without it, adding a doc to `_INTERNAL_FILENAME_PATTERNS` + `MANIFEST.in`
    (the two the footprint doc calls mutually co-required) while forgetting
    `.gitattributes` ships it in the GitHub "Download ZIP" with every test green.

    Spelling-independent by construction: a plain line, a glob, or a directory
    prefix in `.gitattributes` all satisfy it, where the hand-kept alarm above
    only watches plain-file entries.
    """
    internal = sorted(
        rel for rel in _tracked_paths_at_head()
        if surface_contract.classify_release_path(rel) == "internal"
    )
    # Floor re-calibrated 8 -> 7 on 2026-09-21: the findings corpus left the
    # tracked tree for the record branch, so the internal set lost one member.
    assert len(internal) >= 7, (
        "non-vacuity floor: expected at least 7 tracked internal-classified "
        f"files, found {len(internal)} — if the classifier stopped matching, "
        "this test would pass while asserting nothing."
    )
    members = _archive_members(
        _git_archive_to_tar(tmp_path, "HEAD", worktree_attributes=True)
    )
    leaks = sorted(rel for rel in internal if rel in members)
    assert not leaks, (
        "these files classify `internal` but shipped in `git archive` (the "
        "GitHub Download ZIP):\n  " + "\n  ".join(leaks)
        + "\n\nRemediation: add an `<path> export-ignore` line to .gitattributes. "
        "classify_release_path and .gitattributes are independent sister sites; "
        "setting one does not set the other."
    )


def test_no_local_only_classified_tracked_file_ships_in_the_archive(tmp_path):
    """The `local_only` twin of the gate above. Since 2026-09-21 `task-packs/`
    is a MIXED subtree: its ship set is public and everything else under it
    classifies `local_only`, so its `.gitattributes` wall became a named
    deny-list (git cannot re-include inside a pruned directory) that the
    classifier's allow-list outgrows in one `git add -f`. Both review lanes
    drove a force-added spec, a note, a nested findings file and a backup into
    the archive with every other test green; this is the gate that reds on
    them. Non-vacuous today: the ten review scaffolds under `.claude/workflows/`
    are tracked and classify `local_only`."""
    leaky = sorted(
        rel for rel in _tracked_paths_at_head()
        if surface_contract.classify_release_path(rel) == "local_only"
    )
    assert len(leaky) >= 5, (
        "non-vacuity floor: expected at least 5 tracked local_only-classified "
        f"files (the review scaffolds), found {len(leaky)} -- if the classifier "
        "stopped matching, this test would pass while asserting nothing."
    )
    members = _archive_members(
        _git_archive_to_tar(tmp_path, "HEAD", worktree_attributes=True)
    )
    leaks = sorted(rel for rel in leaky if rel in members)
    assert not leaks, (
        "these files classify `local_only` but shipped in `git archive` (the "
        "GitHub Download ZIP):\n  " + "\n  ".join(leaks)
        + "\n\nRemediation: untrack the file (git rm --cached) if it was force-added "
        "by mistake, or add an `export-ignore` row for its family to .gitattributes; "
        "under task-packs/ the ship set is the carve-out in surface_contract."
    )


def test_git_archive_ships_every_packaged_asset(tmp_path):
    """The COMPLEMENT of the export-ignore tests above — and the gap that let
    an unanchored rule prune a shipped package asset.

    Every test in this file so far enumerates what must NOT be in the archive.
    None asserts that what MUST ship actually does, so an ``export-ignore``
    pattern that over-reaches is invisible: the exclusion it was written for
    still works, the suite stays green, and the collateral casualty is only
    discovered by someone unpacking the artifact.

    ``espalier/assets/`` is the package payload ``espalier init`` deploys. A
    missing member there is not cosmetic — ``init`` from a GitHub "Download
    ZIP" dies mid-deploy with a bare ``Errno 2`` after writing a fraction of
    its files, leaving a half-initialized repo.

    Uses ``--worktree-attributes`` so the contract holds against the
    working-tree ``.gitattributes``, matching the sibling tests above.
    """
    result = subprocess.run(
        ["git", "ls-files", "espalier/assets/"],
        cwd=str(REPO_ROOT), capture_output=True, text=True, check=True, timeout=30, encoding="utf-8",
    )
    tracked = sorted(p for p in result.stdout.splitlines() if p)
    # Floor: the contract is vacuous if the asset tree moved or emptied out.
    # 51 tracked assets measured 2026-07-30; the floor guards a silent collapse
    # to zero, it is not a pin on the exact count.
    assert len(tracked) >= 51, (
        f"only {len(tracked)} tracked paths under espalier/assets/ — floor "
        "failed (asset tree moved or emptied?)"
    )

    tar_path = _git_archive_to_tar(tmp_path, "HEAD", worktree_attributes=True)
    members = _archive_members(tar_path)
    dropped = sorted(p for p in tracked if p not in members)
    assert not dropped, (
        "git archive (worktree-attributes) DROPPED packaged assets that "
        "`espalier init` needs:\n  " + "\n  ".join(dropped)
        + "\n\nRemediation: an export-ignore pattern is over-reaching. A rule "
        "meant for a top-level directory needs a LEADING SLASH "
        "(`/task-packs/`, not `task-packs/`) — without it git matches the "
        "directory name at ANY depth, including inside espalier/assets/."
    )


def test_surface_contract_matcher_agrees_with_git_on_every_tracked_path(tmp_path):
    """``surface_contract.matches_export_ignore`` must predict what git really
    prunes — checked against git, over the whole tracked tree.

    This is the gate that was missing when an unanchored ``task-packs/`` pruned
    ``espalier/assets/task-packs/CLAUDE.md`` from the archive. Three shipping
    consumers (``pre_release._find_internal_leaks``,
    ``release_pack``, ``scripts/build_release_archive.py``) ask that matcher
    what git will do, and *nothing* asked git whether the answer was right — so
    the model could disagree with the artifact indefinitely while every
    model-based check stayed green.

    Per-pattern unit assertions live in ``tests/test_pre_release.py``; this is
    the population-level complement. It is the only check here that compares the
    MODEL to the ARTIFACT rather than one artifact view to another.

    **Bounded, and the bound is measured.** Two mutations were driven against
    this test: dropping leading-slash anchoring reds it (naming
    ``espalier/assets/task-packs/CLAUDE.md`` exactly), but letting ``*`` cross
    ``/`` again leaves it GREEN — no tracked path currently exhibits that shape
    (``memory/`` is flat). A matcher defect only shows up here if the live tree
    happens to contain a path that triggers it, so this gate is a floor, never a
    proof of the matcher; the driven unit matrix is what covers the rest.
    """
    tracked = _tracked_paths_at_head()
    # Floor: vacuous if the tree listing broke or collapsed.
    assert len(tracked) >= 900, (
        f"only {len(tracked)} tracked paths at HEAD — floor failed"
    )

    tar_path = _git_archive_to_tar(tmp_path, "HEAD", worktree_attributes=True)
    members = _archive_members(tar_path)
    # Floor: the archive must be a subset of HEAD. A mangled member set (e.g.
    # from mis-parsing a --prefix that is not there) would otherwise read as a
    # huge, meaningless "git pruned everything" and could not fail honestly.
    stray = sorted(members - tracked)
    assert not stray, f"archive members absent from HEAD — probe broken: {stray[:5]}"

    patterns = surface_contract.export_ignore_patterns(REPO_ROOT)
    assert len(patterns) >= 8, (
        f"only {len(patterns)} export-ignore patterns parsed — floor failed"
    )

    disagreements = []
    for rel in sorted(tracked):
        model = any(surface_contract.matches_export_ignore(rel, p) for p in patterns)
        git_pruned = rel not in members
        if model != git_pruned:
            verb = "over-matches (model prunes, git ships)" if model else (
                "under-matches (model ships, git prunes)")
            disagreements.append(f"{rel}: {verb}")
    assert not disagreements, (
        "surface_contract.matches_export_ignore disagrees with git on "
        f"{len(disagreements)} of {len(tracked)} tracked paths:\n  "
        + "\n  ".join(disagreements[:20])
        + "\n\nRemediation: the matcher models git's export-ignore rules "
        "(leading-or-interior slash anchors to root; a trailing slash alone "
        "does not; export-ignore on a directory prunes its subtree; `*` never "
        "crosses `/`). An UNDER-match silently ships internal material; an "
        "OVER-match silently drops a file the payload needs."
    )


def test_claude_workflows_excluded_from_release_surfaces(tmp_path):
    """Internal fan-out review scaffolds under ``.claude/workflows/*.js`` are
    git-TRACKED (transparency) but must never ship to adopters — they are dev
    review tooling (TP-169 vocab + adversarial prompts). They already classify
    ``internal`` for the fusion overlay (fusion_manifest.HARNESS_EXCLUDE +
    test_fuse); this pins the two release sister-surfaces the original exclusion
    MISSED — the bespoke release zip (``classify_release_path`` → ``local_only``)
    and ``git archive`` (the "Download ZIP", via ``.gitattributes`` export-ignore).

    EXHAUSTIVE + floored so a NEW workflow one-shot can never silently leak,
    mirroring ``test_fuse``'s exhaustive overlay-exclusion contract.
    """
    from espalier import surface_contract

    result = subprocess.run(
        ["git", "ls-files", ".claude/workflows/"],
        cwd=str(REPO_ROOT), capture_output=True, text=True, check=True, timeout=30, encoding="utf-8",
    )
    tracked = [p for p in result.stdout.splitlines() if p.endswith(".js")]
    # Floor: the contract is vacuous if there are no tracked workflows at all.
    assert tracked, (
        "no tracked .claude/workflows/*.js found — floor failed (path moved?)"
    )

    # Surface 1 — bespoke release zip enumerates the git index, keyed off classify.
    mis = sorted(p for p in tracked if surface_contract.classify_release_path(p) != "local_only")
    assert not mis, (
        "tracked .claude/workflows/*.js must classify 'local_only' (bespoke "
        "release zip) but these did not:\n  " + "\n  ".join(mis)
        + "\n\nRemediation: ensure '.claude/workflows/' is in "
        "surface_contract._LOCAL_ONLY_PREFIXES."
    )

    # Surface 2 — git archive (GitHub "Download ZIP"), via export-ignore.
    tar_path = _git_archive_to_tar(tmp_path, "HEAD", worktree_attributes=True)
    members = _archive_members(tar_path)
    leaks = sorted(p for p in tracked if p in members)
    assert not leaks, (
        "git archive (worktree-attributes) shipped internal review scaffolds "
        "that should be export-ignored:\n  " + "\n  ".join(leaks)
        + "\n\nRemediation: add `.claude/workflows/ export-ignore` to .gitattributes."
    )


def test_git_archive_contains_required_release_surface(tmp_path):
    """Sanity check the inverse — load-bearing source files DO ship in
    the archive. Catches an over-aggressive .gitignore that excluded
    real source.
    """
    tar_path = _git_archive_to_tar(tmp_path, "HEAD")
    members = _archive_members(tar_path)
    required = (
        "README.md",
        "LICENSE",
        "CHANGELOG.md",
        "pyproject.toml",
        "MANIFEST.in",
        "espalier/__init__.py",
        "espalier/cli.py",
        "espalier/surface_contract.py",
        "tools/cc/hooks/write_guard.py",
        "tools/cc/hooks/stop_gate.py",
    )
    missing = sorted(rel for rel in required if rel not in members)
    assert not missing, (
        "git archive HEAD missing required release surface files:\n  "
        + "\n  ".join(missing)
    )


def test_manifest_single_file_excludes_classify_non_public():
    """TP-184 B8: every single-file ``exclude <path>`` line in MANIFEST.in must
    classify as NON-public (internal / local_only / transient).

    A MANIFEST ``exclude`` that still classifies ``public`` is the TP-176 W1
    class: the file is kept out of the sdist by the exact-exclude, but the
    bespoke release zip (which keys off ``classify_release_path``) and
    ``git archive`` (which honours ``.gitattributes``) still ship it. Binding the
    two surfaces here means a future internal doc added to the MANIFEST excludes
    cannot silently leak through the other release vectors — the gap that let
    docs/REDEFINED_INFORMATION_REGISTRY.md leak (B8).
    """
    from espalier import surface_contract

    manifest = (REPO_ROOT / "MANIFEST.in").read_text(encoding="utf-8")
    offenders = []
    for line in manifest.splitlines():
        # Strip a trailing inline comment FIRST so an annotated exclude
        # (`exclude docs/foo.md  # dev-only`) is still checked, not skipped by the
        # token-count guard below (the latent gap an adversarial pass flagged).
        stripped = line.split("#", 1)[0].strip()
        # Only bare single-file `exclude <path>` lines — not recursive-exclude /
        # prune / global-exclude, which are different (glob/dir) shapes.
        parts = stripped.split()
        if len(parts) != 2 or parts[0] != "exclude":
            continue
        rel = parts[1]
        bucket = surface_contract.classify_release_path(rel)
        if bucket == "public":
            offenders.append(f"{rel} -> classify='public'")
    assert not offenders, (
        "MANIFEST.in `exclude` lines still classify 'public' (kept out of the "
        "sdist but NOT the bespoke release zip / git archive):\n  "
        + "\n  ".join(offenders)
        + "\n\nRemediation: classify the path non-public in "
        "espalier/surface_contract.py (e.g. _INTERNAL_FILENAME_PATTERNS) and add "
        "a .gitattributes export-ignore line if it is tracked."
    )


# ---------------------------------------------------------------------------
# ARCHIVE-03 / ARCLEAK-01 — links must resolve INSIDE the artifact.
#
# Every prior citation-rot round asked "does the cited thing exist?" against the
# WORKING TREE. All of them answered yes and were right. The question none asked
# is "does it exist in the thing we SHIP" — and there the answer was often no,
# because the citer and the cited sit on opposite sides of an export-ignore
# boundary. That class is structurally invisible to `git grep`, to the working
# tree, and to a green suite. Only building the artifact and resolving links
# inside it can see it.
#
# The archive is built from the INDEX (`git write-tree`), not HEAD, so the gate
# answers "what will ship when I commit what I have staged?" — the question an
# operator running the suite before committing actually has. With nothing
# staged the index equals HEAD, so CI behaviour is unchanged.
# ---------------------------------------------------------------------------

# Every entry states WHY. An unexplained exclusion inside a mechanical gate is
# itself an un-tested assertion (and an allowlist that can absorb the whole
# class is how a guard gets neutered on day one).
ARTIFACT_LINK_ALLOWLIST: dict[str, str] = {
    # `espalier/assets/**` are TEMPLATES. Their links are written for the tree
    # `espalier init` deploys them INTO, not for the archive that carries them.
    # Each target below was confirmed present in a real post-`init` repo, so the
    # link resolves for the reader it is written for. Deployment itself is
    # covered by tests/test_adopter_pointer_resolution.py — not by this gate.
    #
    # Until that gate existed the phrase "verified in a driven init" below
    # meant a human drove `init` once and wrote the outcome into this comment,
    # with nothing re-checking it since. It is now re-derived every run against
    # a real driven tree, so these entries are a scope statement rather than an
    # unverified claim.
    "espalier/assets/seed/SHARP_EDGES.md -> sharp-edges/":
        "seed stub; docs/sharp-edges/ is deployed by init (verified in a driven init)",
    "espalier/assets/task-packs/CLAUDE.md -> ../.claude/commands/scope-check.md":
        "seed template; .claude/commands/scope-check.md is deployed by init",
    "espalier/assets/task-packs/CLAUDE.md -> ../.claude/skills/blueprint-authoring/SKILL.md":
        "seed template; .claude/skills/blueprint-authoring/ is deployed by init",
}


def _archive_index_tree(tmp_path: Path) -> Path:
    """Extract `git archive <index tree>` and return the extraction root."""
    tree = subprocess.run(
        ["git", "write-tree"],
        cwd=str(REPO_ROOT), capture_output=True, text=True, check=True, timeout=30, encoding="utf-8",
    ).stdout.strip()
    tar_path = _git_archive_to_tar(tmp_path, tree, worktree_attributes=True)
    dest = tmp_path / "extracted"
    dest.mkdir()
    with tarfile.open(tar_path) as tf:
        tf.extractall(dest, filter="data")
    return dest


def _repo_slug() -> str:
    """``owner/name`` of the public repository, from pyproject's
    ``[project.urls].Repository`` -- derived, so a rename of the public
    repository moves the absolute-link arm with it instead of stranding it."""
    from espalier._compat import tomllib

    assert tomllib is not None, "neither tomllib nor tomli; cannot read pyproject"
    data = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    url = data["project"]["urls"]["Repository"]
    prefix = "https://github.com/"
    assert url.startswith(prefix), url
    return url[len(prefix):].rstrip("/").removesuffix(".git")


class TestArtifactLinksResolveInsideThePayload:
    """No shipped doc may link to something the artifact does not carry."""

    def test_git_archive_has_no_dangling_relative_links(self, tmp_path):
        import sys as _sys

        _sys.path.insert(0, str(Path(__file__).resolve().parent))
        from _artifact_links import dangling_links

        root = _archive_index_tree(tmp_path)
        violations, resolved = dangling_links(root, ARTIFACT_LINK_ALLOWLIST)

        # Non-vacuous floor FIRST: a guard that reds on nothing because it
        # FOUND nothing reads as coverage. Measured population is ~190.
        assert resolved >= 100, (
            f"only {resolved} relative links resolved inside the archive — the "
            "extractor or the payload changed and this gate is now near-vacuous. "
            "Fix the extractor; do not lower this floor."
        )

        assert not violations, (
            "shipped doc(s) link to a target the archive does not carry. A "
            "reader of the GitHub 'Download ZIP' gets a 404 while the working "
            "tree resolves fine — which is why no other check sees this. Either "
            "de-link / repoint at a shipped target, or add an "
            "ARTIFACT_LINK_ALLOWLIST entry WITH A STATED REASON:\n  "
            + "\n  ".join(violations)
        )

    def test_git_archive_has_no_absolute_link_to_an_unshipped_path(self, tmp_path):
        """The absolute-link twin of the arm above.

        The relative arm skips ``https://``; the front-door docs link by the
        absolute GitHub form, and under ``DEC-31`` the public repository IS the
        archive extract, so an absolute link whose ``<path>`` classifies
        ``internal`` or ``local_only`` 404s for every reader of the public repo
        while resolving in this dev tree. Earned red 2026-09-22 on the live
        index tree: ``docs/CONVENTIONS.md`` linked
        ``.../blob/main/docs/REDEFINED_INFORMATION_REGISTRY.md`` (internal) and
        said "the absolute link resolves on GitHub" -- the retired model.
        """
        import sys as _sys

        _sys.path.insert(0, str(Path(__file__).resolve().parent))
        from _artifact_links import absolute_links_to_unshipped_paths

        root = _archive_index_tree(tmp_path)
        violations, checked = absolute_links_to_unshipped_paths(
            root, _repo_slug(), surface_contract.classify_release_path
        )
        # Non-vacuous floor: 26 absolute links into this repository across the
        # public docs on 2026-09-22, most of them README.md's.
        assert checked >= 15, (
            f"only {checked} absolute links into this repository were found in the "
            "archive's docs — the extractor, the slug or the payload changed and "
            "this arm is near-vacuous. Fix the extractor; do not lower this floor."
        )
        assert not violations, (
            "shipped doc(s) link absolutely to a path the public repository does "
            "not carry (the bucket in parentheses is classify_release_path's). "
            "De-link it or repoint at a public path:\n  " + "\n  ".join(violations)
        )

    def test_an_absolute_link_to_an_internal_path_is_named(self, tmp_path):
        """Earn the red: ``docs/RELEASE_CHECKLIST.md`` (internal) linked
        absolutely from a scratch copy of a public doc reds naming the citer,
        the link and the bucket; the public sibling beside it passes."""
        import sys as _sys

        _sys.path.insert(0, str(Path(__file__).resolve().parent))
        from _artifact_links import absolute_links_to_unshipped_paths

        slug = _repo_slug()
        scratch = tmp_path / "scratch" / "docs"
        scratch.mkdir(parents=True)
        (scratch / "README.md").write_text(
            f"See [the checklist](https://github.com/{slug}/blob/main/docs/RELEASE_CHECKLIST.md) "
            f"and [the hooks](https://github.com/{slug}/blob/main/docs/HOOKS.md).\n"
            f"Not ours: [x](https://github.com/someone-else/repo/blob/main/docs/RELEASE_CHECKLIST.md)\n"
            f"```\nhttps://github.com/{slug}/blob/main/docs/RELEASE_DECISIONS.md\n```\n"
            # a bare URL ending a sentence, and an autolink: the punctuation is
            # not part of the path (the review's two misses)
            f"The decisions are at https://github.com/{slug}/blob/main/docs/RELEASE_DECISIONS.md.\n"
            f"Autolink: <https://github.com/{slug}/blob/main/docs/RELEASE_CHECKLIST.md>\n",
            encoding="utf-8",
        )
        violations, checked = absolute_links_to_unshipped_paths(
            scratch.parent, slug, surface_contract.classify_release_path
        )
        assert checked == 4, checked  # the foreign repo and the fenced URL are not counted
        assert len(violations) == 3 and all("(internal)" in v for v in violations), violations
        assert violations[0] == (
            f"docs/README.md -> https://github.com/{slug}/blob/main/docs/RELEASE_CHECKLIST.md (internal)"
        )
        assert "RELEASE_DECISIONS.md" in violations[1] and "RELEASE_CHECKLIST.md" in violations[2], violations

    def test_every_allowlist_entry_carries_a_reason(self):
        """The allowlist may not grow silent entries."""
        unexplained = [k for k, v in ARTIFACT_LINK_ALLOWLIST.items() if not v.strip()]
        assert not unexplained, (
            "ARTIFACT_LINK_ALLOWLIST entries without a stated reason: "
            f"{unexplained}. An exclusion inside a mechanical gate is itself an "
            "un-tested assertion."
        )

    def test_allowlist_has_no_dead_entries(self, tmp_path):
        """An allowlist entry whose violation no longer occurs must be removed.

        Otherwise the allowlist accretes permanently and quietly widens the
        hole it was scoped to cover.
        """
        import sys as _sys

        _sys.path.insert(0, str(Path(__file__).resolve().parent))
        from _artifact_links import dangling_links

        root = _archive_index_tree(tmp_path)
        live, _ = dangling_links(root, {})
        dead = sorted(set(ARTIFACT_LINK_ALLOWLIST) - set(live))
        assert not dead, (
            "ARTIFACT_LINK_ALLOWLIST carries entries that no longer correspond "
            f"to a real dangling link — remove them: {dead}"
        )
