"""TP-03 Phase 5 — unit tests for espalier.managed_markers.

The marker module is the SoT for the ``espalier:managed`` ownership
contract. These tests pin the constants, the recognition logic
(frontmatter-aware scan), and the insertion helpers (idempotent;
preserve YAML frontmatter; shebang-safe text variant).
"""
from __future__ import annotations

import ast
from pathlib import Path

import pytest

from espalier.managed_markers import (
    JSON_SENTINEL_KEY,
    MANAGED_MARKER,
    MARKER_HASH_COMMENT,
    MARKER_HTML_COMMENT_RICH,
    MARKER_HTML_COMMENT_SHORT,
    apply_marker_to_md,
    apply_marker_to_text,
    has_managed_marker,
)


# ---------------------------------------------------------------------------
# Constants — pin the operator-visible marker text
# ---------------------------------------------------------------------------


class TestConstants:
    def test_managed_marker_value(self):
        assert MANAGED_MARKER == "espalier:managed"

    def test_html_comment_rich_includes_marker(self):
        assert MANAGED_MARKER in MARKER_HTML_COMMENT_RICH
        assert "regenerated by" in MARKER_HTML_COMMENT_RICH

    def test_html_comment_short_includes_marker(self):
        assert MARKER_HTML_COMMENT_SHORT == f"<!-- {MANAGED_MARKER} -->"

    def test_hash_comment_form(self):
        assert MARKER_HASH_COMMENT == f"# {MANAGED_MARKER}"

    def test_json_sentinel_key(self):
        assert JSON_SENTINEL_KEY == "_espalier_managed"


# ---------------------------------------------------------------------------
# JSON_SENTINEL_KEY is the *real* single source of truth (TP-313c B)
# ---------------------------------------------------------------------------


class TestJsonSentinelIsRealSoT:
    """The settings sentinel must route through ``JSON_SENTINEL_KEY``, not a
    hardcoded ``"_espalier_managed"`` literal duplicated per reader/writer.

    An exported "single source of truth" constant that no reader imports is
    worse than the literal it claims to replace — it *claims* a centralization
    the code does not have. This pins the routing: every production
    reader/writer imports the constant, and the bare literal appears in NO
    espalier/ code outside ``managed_markers.py`` (its definer). Comments are
    exempt (not AST nodes); markdown assets and test fixtures keep the literal
    deliberately as independent oracles (a test routing through the constant
    would be circular).
    """

    @staticmethod
    def _repo_root() -> Path:
        return Path(__file__).resolve().parent.parent

    def test_production_readers_import_the_constant(self):
        root = self._repo_root()
        for mod in ("espalier/cli.py", "espalier/cleanup.py"):
            src = (root / mod).read_text(encoding="utf-8")
            assert "JSON_SENTINEL_KEY" in src, (
                f"{mod} must route the settings sentinel through "
                "JSON_SENTINEL_KEY, not a hardcoded literal"
            )

    @staticmethod
    def _sentinel_literal_lines(source: str) -> list[int]:
        """Line numbers where the sentinel literal appears as a string Constant
        in ``source``'s AST (comments/prose are not AST nodes, so exempt)."""
        tree = ast.parse(source)
        return [
            node.lineno
            for node in ast.walk(tree)
            if isinstance(node, ast.Constant)
            and isinstance(node.value, str)
            and node.value == "_espalier_managed"
        ]

    def test_scan_actually_fires_on_a_planted_literal(self):
        # Negative fixture: the absence assertion below is only meaningful if the
        # AST scan genuinely detects a hardcoded literal. Prove it fires on one
        # and does NOT fire on the routed constant — otherwise the gate is vacuous.
        assert self._sentinel_literal_lines('data["_espalier_managed"] = True') == [1]
        assert self._sentinel_literal_lines("data[JSON_SENTINEL_KEY] = True") == []

    def test_literal_appears_in_no_production_code(self):
        root = self._repo_root()
        offenders: list[str] = []
        scanned = 0
        for path in sorted((root / "espalier").rglob("*.py")):
            rel = path.relative_to(root).as_posix()
            if "/_vendor/" in f"/{rel}":
                continue  # tools mirror — governed by tools/cc rules
            if rel == "espalier/managed_markers.py":
                continue  # the definer legitimately owns the literal
            try:
                source = path.read_text(encoding="utf-8")
            except OSError:
                continue
            scanned += 1
            try:
                offenders += [f"{rel}:{ln}" for ln in self._sentinel_literal_lines(source)]
            except SyntaxError:
                continue
        # Scan-witness: without this, a broken walker (0 files) passes vacuously.
        assert scanned > 10, (
            f"walker visited only {scanned} espalier/*.py files — the absence "
            "assertion would be vacuous; the scan is broken"
        )
        assert not offenders, (
            "the settings sentinel literal is hardcoded in production code "
            f"instead of routing through JSON_SENTINEL_KEY: {offenders}"
        )


# ---------------------------------------------------------------------------
# has_managed_marker
# ---------------------------------------------------------------------------


class TestHasManagedMarker:
    def test_recognizes_html_comment_at_top(self):
        text = f"<!-- {MANAGED_MARKER} -->\n# heading\n"
        assert has_managed_marker(text) is True

    def test_recognizes_hash_comment_at_top(self):
        text = f"# {MANAGED_MARKER}\nx = 1\n"
        assert has_managed_marker(text) is True

    def test_unmarked_returns_false(self):
        assert has_managed_marker("# unmanaged content\n") is False

    def test_empty_returns_false(self):
        assert has_managed_marker("") is False

    def test_recognizes_marker_after_short_frontmatter(self):
        text = (
            "---\nname: foo\nmodel: opus\n---\n"
            f"<!-- {MANAGED_MARKER} -->\n# body\n"
        )
        assert has_managed_marker(text) is True

    def test_recognizes_marker_after_long_frontmatter(self):
        # Build a frontmatter block ~1500 bytes long — well past the
        # default scan window, exercising the post-frontmatter padding.
        body = "\n".join(f"  field{i}: x" * 4 for i in range(100))
        text = (
            f"---\nname: foo\ndescription: |\n{body}\nmodel: opus\n---\n"
            f"<!-- {MANAGED_MARKER} -->\n# body\n"
        )
        assert has_managed_marker(text) is True

    def test_marker_buried_past_scan_window_not_detected(self):
        # No frontmatter, marker placed deep in the body — counts as a body
        # mention, not an ownership signal.
        padding = "x = 1\n" * 200
        text = f"{padding}# {MANAGED_MARKER}\n"
        assert has_managed_marker(text) is False

    def test_explicit_scan_chars_override(self):
        # Caller can request a wider scan window when needed.
        # 200 lines * 8 chars = 1600 chars padding — well past the default
        # 600-byte window but within an explicit 2000.
        text = "padding\n" * 200 + f"# {MANAGED_MARKER}\n"
        assert has_managed_marker(text) is False
        assert has_managed_marker(text, scan_chars=2000) is True


# ---------------------------------------------------------------------------
# apply_marker_to_md — frontmatter-aware insertion
# ---------------------------------------------------------------------------


class TestApplyMarkerToMd:
    def test_no_frontmatter_marker_at_top(self):
        result = apply_marker_to_md("# title\nbody\n")
        assert result.startswith(MARKER_HTML_COMMENT_RICH)

    def test_frontmatter_marker_after_close(self):
        content = (
            "---\nname: foo\ndescription: bar\nmodel: opus\n---\n# Body\n"
        )
        result = apply_marker_to_md(content)
        # Frontmatter must remain intact at the top
        assert result.startswith("---\n")
        assert "name: foo" in result.split("\n---\n")[0]
        # Marker line is on the line after the closing ---
        head, _, tail = result.partition("\n---\n")
        assert tail.startswith(MARKER_HTML_COMMENT_RICH)

    # An EMPTY frontmatter breaks in two different places, so both rows below
    # fail for DIFFERENT reasons — which is the proof this is two branches, not
    # one. `---\n---\n`: the closing delimiter starts at index 3, but the search
    # began at 4, so the block read as "no frontmatter" and the marker was
    # PREPENDED above line 1, invalidating the YAML. `---\n---` (delimiter at
    # EOF, no trailing newline): the index is already correct, but `head` ends
    # in `---`, so the marker was GLUED onto the delimiter line.
    @pytest.mark.parametrize("body", ["---\n---\n", "---\n---"])
    def test_empty_frontmatter_marker_lands_below_the_closing_delimiter(self, body):
        out = apply_marker_to_md(body, comment="<!-- M -->")
        # Glue check FIRST: ordered this way each row reds on its OWN mechanism
        # (row 2 on the glue, row 1 on the prepend). With startswith first, row 2
        # short-circuits on it and the glue defect never gets named.
        assert "---<!-- M -->" not in out, out
        assert out.startswith("---\n---\n"), out

    def test_idempotent_no_double_insertion(self):
        text = "# already managed\n"
        once = apply_marker_to_md(text)
        twice = apply_marker_to_md(once)
        assert once == twice

    def test_idempotent_with_frontmatter(self):
        content = "---\nname: foo\nmodel: opus\n---\n# body\n"
        once = apply_marker_to_md(content)
        twice = apply_marker_to_md(once)
        assert once == twice

    def test_preserves_yaml_frontmatter_validity(self):
        # The agent loader parses YAML between the leading ---/--- pair.
        # Marker insertion must not introduce content before or inside
        # the frontmatter that would break parsing.
        content = "---\nname: r\ndescription: d\nmodel: opus\n---\nbody\n"
        result = apply_marker_to_md(content)
        # Opening delimiter still at byte 0
        assert result.startswith("---\n")
        # Closing delimiter still present and parseable
        end = result.find("\n---\n", 4)
        assert end > 0
        # Content between the two --- delimiters is byte-identical to the
        # original frontmatter (no smuggled marker line, no rewriting).
        original_frontmatter = content[:content.find("\n---\n", 4)]
        new_frontmatter = result[:end]
        assert new_frontmatter == original_frontmatter

    def test_custom_comment_form_used(self):
        result = apply_marker_to_md(
            "# x\n", comment=MARKER_HTML_COMMENT_SHORT,
        )
        assert result.startswith(MARKER_HTML_COMMENT_SHORT)
        assert MARKER_HTML_COMMENT_RICH not in result


# ---------------------------------------------------------------------------
# apply_marker_to_text — shebang-aware
# ---------------------------------------------------------------------------


class TestApplyMarkerToText:
    def test_plain_text_marker_at_top(self):
        result = apply_marker_to_text("x = 1\n")
        assert result.startswith(MARKER_HASH_COMMENT)

    def test_shebang_preserved(self):
        result = apply_marker_to_text("#!/usr/bin/env python3\nx = 1\n")
        assert result.startswith("#!/usr/bin/env python3\n")
        # Marker on the immediate next line
        second_line = result.split("\n", 2)[1]
        assert second_line == MARKER_HASH_COMMENT

    def test_idempotent(self):
        text = "x = 1\n"
        once = apply_marker_to_text(text)
        twice = apply_marker_to_text(once)
        assert once == twice


class TestApplyMarkerToBatch:
    """DEF-729: the Windows statusline shim is a batch file. To cmd.exe a
    ``#`` line is a command, and every line before ``@echo off`` is echoed to
    stdout -- the statusline's own channel -- so the batch marker is ``::``
    and it goes on the line AFTER a leading echo-off."""

    def test_marker_lands_after_a_leading_echo_off(self):
        from espalier.managed_markers import MARKER_BATCH_COMMENT, apply_marker_to_batch, has_managed_marker

        result = apply_marker_to_batch("@echo off\nsetlocal\nrem x\n")
        lines = result.split("\n")
        assert lines[0] == "@echo off"
        assert lines[1] == MARKER_BATCH_COMMENT
        assert lines[2] == "setlocal"
        assert has_managed_marker(result)

    def test_echo_off_is_matched_the_way_cmd_reads_it(self):
        from espalier.managed_markers import MARKER_BATCH_COMMENT, apply_marker_to_batch

        result = apply_marker_to_batch("  @ECHO OFF\nx\n")
        assert result.split("\n")[1] == MARKER_BATCH_COMMENT

    def test_marker_goes_on_top_when_there_is_no_echo_off(self):
        from espalier.managed_markers import MARKER_BATCH_COMMENT, apply_marker_to_batch

        result = apply_marker_to_batch("python x.py\n")
        assert result.startswith(MARKER_BATCH_COMMENT + "\n")

    def test_idempotent(self):
        from espalier.managed_markers import apply_marker_to_batch

        once = apply_marker_to_batch("@echo off\nx\n")
        assert apply_marker_to_batch(once) == once

    def test_the_source_shim_carries_no_marker_and_the_deployed_copy_does(self):
        """The tools/cc/ source is the SoT and never carries a marker (its
        rem lines mention the marker only mid-line, which the anchored
        pattern must not read); the deploy inserts one."""
        from pathlib import Path

        from espalier.managed_markers import apply_marker_to_batch, has_managed_marker
        from espalier.managed_paths import STATUSLINE_SHIM

        source = (Path(__file__).resolve().parent.parent / STATUSLINE_SHIM).read_text(encoding="utf-8")
        assert not has_managed_marker(source)
        assert has_managed_marker(apply_marker_to_batch(source))


# ---------------------------------------------------------------------------
# TP-54 BC-026 — regression suite for line-anchored recognition
# ---------------------------------------------------------------------------


class TestLineAnchoredRecognition:
    """The marker must match only as an anchored comment line.

    BC-026: a YAML scalar, prose paragraph, or JSON value referencing
    ``espalier:managed`` as text used to count as a marker (substring
    match). Hostile assets shipped via PR could thus impersonate
    managed files and become overwritable by ``espalier init``. The
    fix anchors recognition to ``^[ \\t]*(?:#|<!--|::)`` line starts (a shell,
    HTML or batch-file comment head).
    """

    def test_yaml_scalar_substring_rejected(self):
        text = "---\ndescription: compatible with espalier:managed projects\n---\nbody\n"
        assert has_managed_marker(text) is False

    def test_prose_paragraph_substring_rejected(self):
        text = "# title\n\nThis tool uses espalier:managed markers to track ownership.\n"
        assert has_managed_marker(text) is False

    def test_json_string_value_rejected(self):
        text = '{"description": "espalier:managed"}\n'
        assert has_managed_marker(text) is False

    def test_alternate_comment_char_rejected(self):
        assert has_managed_marker("// espalier:managed\nbody\n") is False
        assert has_managed_marker("; espalier:managed\nbody\n") is False
        assert has_managed_marker("/* espalier:managed */\nbody\n") is False

    def test_case_sensitive(self):
        assert has_managed_marker("# Espalier:Managed\n") is False
        assert has_managed_marker("# ESPALIER:MANAGED\n") is False

    def test_mid_line_marker_rejected(self):
        text = "some prefix # espalier:managed\nbody\n"
        assert has_managed_marker(text) is False

    def test_trailing_text_after_canonical_marker_ok(self):
        assert has_managed_marker("# espalier:managed extra commentary\n") is True

    def test_word_boundary_blocks_adjacent_alphanumeric(self):
        assert has_managed_marker("# espalier:managed42\n") is False
        assert has_managed_marker("# espalier:managedx\n") is False

    def test_leading_tab_tolerated(self):
        assert has_managed_marker("\t# espalier:managed\n") is True
        assert has_managed_marker("\t\t<!-- espalier:managed -->\n") is True

    def test_zero_width_space_as_leading_whitespace_rejected(self):
        text = "\u200b# espalier:managed\n"
        assert has_managed_marker(text) is True, (
            "ZWSP is default-ignorable (Cf) and must be stripped from file head, "
            "not treated as line-displacing content"
        )

    def test_canonical_hash_form_matches(self):
        assert has_managed_marker("# espalier:managed\n") is True

    def test_canonical_html_short_form_matches(self):
        assert has_managed_marker("<!-- espalier:managed -->\n") is True

    def test_canonical_batch_form_matches(self):
        assert has_managed_marker(":: espalier:managed\n") is True

    def test_canonical_html_rich_form_matches(self):
        text = (
            "<!-- espalier:managed - regenerated by `espalier init`; "
            "edit at your own risk -->\n"
        )
        assert has_managed_marker(text) is True


# ---------------------------------------------------------------------------
# TP-54 — legacy substring helper migration assertion
# ---------------------------------------------------------------------------


class TestLegacySubstringHelperIsolated:
    """The pre-TP-54 substring code path survives only as
    ``_legacy_substring_match`` for migration assertion. The public
    API must NOT route through it.
    """

    def test_legacy_helper_still_matches_substring(self):
        from espalier.managed_markers import _legacy_substring_match
        text = "---\ndescription: espalier:managed text\n---\n"
        assert _legacy_substring_match(text) is True

    def test_public_api_diverges_from_legacy_on_bc026_input(self):
        from espalier.managed_markers import _legacy_substring_match
        text = "---\ndescription: espalier:managed text\n---\n"
        assert _legacy_substring_match(text) is True
        assert has_managed_marker(text) is False, (
            "BC-026 regression: public has_managed_marker must not "
            "recognize substring-in-YAML; only _legacy_substring_match "
            "(retained for migration testing) returns True for this input"
        )


# ---------------------------------------------------------------------------
# TP-54 sub-task 1-G — confusable-marker loud-warning surface
# ---------------------------------------------------------------------------


class TestConfusableDetection:
    """Loud-warning surface for visual-near-marker patterns.

    These do NOT match the anchored regex (so the file is treated as
    not-managed, which is the secure outcome). The warning catches the
    case where a maintainer's eye sees the confusable in a PR diff and
    approves it as if it were a real marker — at which point the asset
    would be silently not-managed and future ``espalier init`` reruns
    would skip it (silent disable).
    """

    def test_cyrillic_confusable_first_char_flagged(self):
        from espalier.managed_markers import find_confusable_markers
        content = "# \u0435spalier:managed\n"
        findings = find_confusable_markers(content)
        assert findings, "Cyrillic-first-char confusable not surfaced"

    def test_mid_word_cyrillic_flagged(self):
        from espalier.managed_markers import find_confusable_markers
        content = "# esp\u0430lier:managed\n"
        findings = find_confusable_markers(content)
        assert findings, "mid-word Cyrillic confusable not surfaced"

    def test_multiple_cyrillic_substitutions_flagged(self):
        from espalier.managed_markers import find_confusable_markers
        content = "# esp\u0430lier:m\u0430n\u0430ged\n"
        findings = find_confusable_markers(content)
        assert findings, "multi-Cyrillic confusable not surfaced"

    def test_uppercase_variant_flagged(self):
        from espalier.managed_markers import find_confusable_markers
        content = "# Espalier:Managed\n"
        findings = find_confusable_markers(content)
        assert findings, "case-variant confusable not surfaced (matches via mixed-case regex character classes)"

    def test_html_entity_flagged(self):
        from espalier.managed_markers import find_confusable_markers
        content = "# &#x65;spalier:managed\n"
        findings = find_confusable_markers(content)
        assert findings, "HTML-entity confusable not surfaced"

    def test_html_entity_decimal_flagged(self):
        from espalier.managed_markers import find_confusable_markers
        content = "# &#101;spalier:managed\n"
        findings = find_confusable_markers(content)
        assert findings, "decimal HTML-entity confusable not surfaced"

    def test_canonical_marker_not_flagged(self):
        from espalier.managed_markers import find_confusable_markers
        assert find_confusable_markers("# espalier:managed\n") == []
        assert find_confusable_markers("<!-- espalier:managed -->\n") == []

    def test_unrelated_content_not_flagged(self):
        from espalier.managed_markers import find_confusable_markers
        assert find_confusable_markers("# arbitrary heading\n") == []
        assert find_confusable_markers("") == []

    def test_findings_include_line_number(self):
        from espalier.managed_markers import find_confusable_markers
        content = "\n\n\n# \u0435spalier:managed\n"
        findings = find_confusable_markers(content)
        assert findings
        assert findings[0][1] == 4, (
            f"line number wrong: expected 4, got {findings[0][1]}"
        )

    def test_assets_have_no_confusables_at_release(self):
        """Contract test: shipped ``.md`` assets in ``espalier/assets/``
        must use canonical markers. Prevents a maintainer from
        accidentally shipping a confusable that would render the asset
        not-managed at recognition time.
        """
        from pathlib import Path

        from espalier.managed_markers import find_confusable_markers
        assets_dir = Path(__file__).parent.parent / "espalier" / "assets"
        offenders = []
        for path in assets_dir.rglob("*.md"):
            content = path.read_text(encoding="utf-8")
            confusables = find_confusable_markers(content)
            if confusables:
                offenders.append((path, confusables))
        assert not offenders, (
            "Shipped assets contain confusable markers:\n"
            + "\n".join(f"  {p}: {c}" for p, c in offenders)
        )

    def test_bom_prefix_does_not_demote_managed(self):
        """Round-2 finding (TP-54): a leading UTF-8 BOM would otherwise
        displace the ``^`` anchor and silently turn an existing managed
        file user-modified on next deploy."""
        canonical = "# espalier:managed\nbody\n"
        with_bom = "\ufeff" + canonical
        assert has_managed_marker(canonical) is True
        assert has_managed_marker(with_bom) is True, (
            "BOM-prefixed managed file silently demoted to user-modified"
        )

    @pytest.mark.parametrize("prefix", [
        "\ufeff",       # BOM (round-2)
        "\u200b",       # ZWSP (round-3)
        "\u200c",       # ZWNJ (round-3)
        "\u200d",       # ZWJ (round-3)
        "\u200e",       # LRM (round-3)
        "\u200f",       # RLM (round-3)
        "\u2028",       # LINE SEPARATOR (round-3)
        "\u2029",       # PARAGRAPH SEPARATOR (round-3)
        "\u202a",       # LEFT-TO-RIGHT EMBEDDING (round-3)
        "\u202e",       # RIGHT-TO-LEFT OVERRIDE (round-3)
        "\u2060",       # WORD JOINER (round-4; ZWSP successor)
        "\u2061",       # FUNCTION APPLICATION (round-4)
        "\u00ad",       # SOFT HYPHEN (round-4)
        "\u180e",       # MONGOLIAN VOWEL SEPARATOR (round-4)
        "\ufff9",       # INTERLINEAR ANNOTATION ANCHOR (round-4)
        "\u2066",       # LRI (round-4)
        "\u2069",       # PDI (round-4)
        "\ufeff\u200b\u2060",  # BOM + ZWSP + WORD JOINER combined
    ])
    def test_invisible_prefix_does_not_demote_managed(self, prefix):
        """Round-3/4 widening (TP-54 asymptote): not just BOM — ANY
        invisible / zero-width / bidi-control / default-ignorable
        codepoint at file start would displace the ``^`` anchor
        pre-fix."""
        canonical = "# espalier:managed\nbody\n"
        prefixed = prefix + canonical
        assert has_managed_marker(prefixed) is True, (
            f"Managed file silently demoted by invisible prefix "
            f"U+{ord(prefix[0]):04X}{'+...' if len(prefix) > 1 else ''}"
        )


# ---------------------------------------------------------------------------
# Seed-version stamp — the CONTENT key for "harness-provenance, adopter-owned"
# ---------------------------------------------------------------------------


def _stamped(body: str, version: str = "0.8.0a13") -> str:
    import hashlib

    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    return f"<!-- espalier:seed-version v{version} sha256:{digest} -->\n{body}"


class TestSeedStamp:
    """DEF-686 / DEF-687: one owner for the seed stamp, readable without cli."""

    def test_cli_regex_is_the_same_object(self):
        from espalier import cli
        from espalier.managed_markers import SEED_STAMP_RE

        assert cli._SEED_STAMP_RE is SEED_STAMP_RE

    def test_digest_and_presence(self):
        from espalier.managed_markers import has_seed_stamp, seed_stamp_digest

        text = _stamped("# Doc\n")
        assert has_seed_stamp(text)
        assert seed_stamp_digest(text) == text.split("sha256:")[1].split(" ")[0]
        assert not has_seed_stamp("# Doc\n")
        assert seed_stamp_digest("# Doc\n") is None

    def test_managed_marker_is_not_a_seed_stamp(self):
        from espalier.managed_markers import MARKER_HTML_COMMENT_SHORT, has_seed_stamp

        assert not has_seed_stamp(MARKER_HTML_COMMENT_SHORT + "\n# Doc\n")

    def test_stamp_must_be_the_first_line(self):
        from espalier.managed_markers import has_seed_stamp

        assert not has_seed_stamp("\n" + _stamped("# Doc\n"))

    def test_untouched_vs_edited_vs_unstamped(self):
        from espalier.managed_markers import seed_is_untouched

        text = _stamped("# Conventions\n\n- one\n")
        assert seed_is_untouched(text)
        assert not seed_is_untouched(text + "- operator added a line\n")
        assert not seed_is_untouched("# Conventions\n\n- one\n")

    def test_path_predicate_reads_only_the_head(self, tmp_path: Path):
        from espalier.managed_markers import SEED_STAMP_SCAN_BYTES, path_has_seed_stamp

        big = tmp_path / "big.md"
        big.write_text(_stamped("x" * 300_000), encoding="utf-8")
        assert path_has_seed_stamp(big)
        # a long version string still fits the peek window
        longv = tmp_path / "longv.md"
        longv.write_text(_stamped("body\n", version="0.8.0a13.post1+local.build.9999"), encoding="utf-8")
        assert len(longv.read_text(encoding="utf-8").splitlines()[0]) < SEED_STAMP_SCAN_BYTES
        assert path_has_seed_stamp(longv)

    def test_path_predicate_refuses_what_it_cannot_read(self, tmp_path: Path):
        from espalier.managed_markers import path_has_seed_stamp

        assert not path_has_seed_stamp(tmp_path / "missing.md")
        assert not path_has_seed_stamp(tmp_path)  # a directory
        binary = tmp_path / "blob.md"
        binary.write_bytes(b"\x00\xff" * 40)
        assert not path_has_seed_stamp(binary)
        plain = tmp_path / "plain.md"
        plain.write_text("# Mine\n", encoding="utf-8")
        assert not path_has_seed_stamp(plain)

    def test_crlf_resave_is_still_a_stamp(self, tmp_path: Path):
        """Review catch: a Windows editor resaving a seed with CRLF (and/or a
        BOM) is not an edit. The byte-mode peek must fold line endings the way
        text-mode readers already do, or the seed re-enters the fingerprint."""
        from espalier.managed_markers import has_seed_stamp, path_has_seed_stamp, seed_is_untouched

        lf = _stamped("# Doc\n\nline\n")
        crlf = lf.replace("\n", "\r\n")
        bom_crlf = "\ufeff" + crlf
        for variant in (crlf, bom_crlf):
            assert has_seed_stamp(variant)
            assert seed_is_untouched(variant)
        f = tmp_path / "seed.md"
        f.write_bytes(crlf.encode("utf-8"))
        assert path_has_seed_stamp(f)
        f.write_bytes(bom_crlf.encode("utf-8"))
        assert path_has_seed_stamp(f)
