"""TP-06 — repo-mode classifier + source-checkout doctor semantics.

A clean source checkout (committed surface present, no runtime artifacts)
must not fail doctor — the gitignored runtime files (`.claude/settings.json`,
`reports/*.json`, `.espalier/integrity.json`) are generated by `init`, not
required source files. CI runs doctor on fresh clones; this contract
guarantees those invocations exit 0.

Initialized repos still get the full check; partial init is still a real
failure.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

from espalier.doctor import (
    REPO_MODE_INITIALIZED_CONSUMER,
    REPO_MODE_INITIALIZED_SELF_HOST,
    REPO_MODE_SOURCE_CHECKOUT,
    REPO_MODE_UNINITIALIZED,
    _detect_repo_mode,
    run_doctor_check,
)

from tests._git_oracle import require_tracked_paths

REPO_ROOT = Path(__file__).resolve().parent.parent

# Marker assignment lives in tests/conftest.py::_MARKER_RULES.


def _empty_target(tmp_path: Path) -> Path:
    target = tmp_path / "empty"
    target.mkdir()
    return target


def _source_checkout_target(tmp_path: Path) -> Path:
    """Mirror the espalier-harness repo as a fresh `git clone` has it.

    Derived, not listed: the copy is exactly the tracked set -- `git ls-files`
    through the tree's git oracle, so a foreign or empty answer raises instead
    of yielding a hollow tree that still passes -- plus a fresh `git init`.
    Until 2026-09-13 this was a copytree over the working tree with a hand-kept
    exclusion list, and every "clean" copy carried 267 untracked files (the
    blueprint chain, the bench results, session state, nested caches), because
    a two-segment name in a root-only set never matches a directory listing
    (DEF-481). Symlinks are copied as links, never followed.
    """
    tracked = require_tracked_paths(REPO_ROOT, minimum=200, what="tracked files")
    target = tmp_path / "tree"
    for rel in tracked:
        dst = target / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(REPO_ROOT / rel, dst, follow_symlinks=False)
    subprocess.run(["git", "init", "-q"], cwd=str(target), check=True)
    return target


def _initialized_self_host(tmp_path: Path) -> Path:
    """A source-checkout target with `espalier init .` applied."""
    target = _source_checkout_target(tmp_path)
    subprocess.run(
        [sys.executable, "-m", "espalier.cli", "init", "."],
        cwd=str(target), check=True, capture_output=True, timeout=120,
    )
    return target


# ---------------------------------------------------------------------------
# _detect_repo_mode — pure classifier
# ---------------------------------------------------------------------------


class TestDetectRepoMode:
    def test_empty_repo_is_uninitialized(self, tmp_path):
        target = _empty_target(tmp_path)
        assert _detect_repo_mode(target) == REPO_MODE_UNINITIALIZED

    def test_bare_reports_dir_is_still_uninitialized(self, tmp_path):
        """TP-152 E-5: a fresh adopter repo that keeps its own bare
        `reports/` dir (no espalier fingerprint artifact) must stay
        UNINITIALIZED. Pre-fix the bare dir was a runtime marker, flipping
        the repo out of the gentle-guidance path into a failure state."""
        target = _empty_target(tmp_path)
        (target / "reports").mkdir()
        (target / "reports" / "coverage.xml").write_text("x", encoding="utf-8")
        assert _detect_repo_mode(target) == REPO_MODE_UNINITIALIZED

    def test_clean_checkout_is_source_checkout(self, tmp_path):
        target = _source_checkout_target(tmp_path)
        assert _detect_repo_mode(target) == REPO_MODE_SOURCE_CHECKOUT

    def test_self_host_after_init_is_initialized_self_host(self, tmp_path):
        target = _initialized_self_host(tmp_path)
        assert _detect_repo_mode(target) == REPO_MODE_INITIALIZED_SELF_HOST

    def test_consumer_repo_after_init_is_initialized_consumer(self, tmp_path):
        # User repo (not espalier-harness) with init applied
        target = tmp_path / "user-repo"
        target.mkdir()
        (target / "README.md").write_text("# user\n", encoding="utf-8")
        (target / "pyproject.toml").write_text(
            '[project]\nname = "my-project"\n', encoding="utf-8",
        )
        subprocess.run(["git", "init", "-q", str(target)], check=True)
        subprocess.run(
            [sys.executable, "-m", "espalier.cli", "init", str(target)],
            check=True, capture_output=True, timeout=120,
        )
        assert _detect_repo_mode(target) == REPO_MODE_INITIALIZED_CONSUMER


# ---------------------------------------------------------------------------
# run_doctor_check — source_checkout mode does not require runtime files
# ---------------------------------------------------------------------------


class TestSourceCheckoutDoctor:
    def test_clean_checkout_passes(self, tmp_path):
        target = _source_checkout_target(tmp_path)
        report = run_doctor_check(target)
        assert report["mode"] == REPO_MODE_SOURCE_CHECKOUT
        assert report["status"] == "pass"
        assert not report["failures"]

    def test_clean_checkout_primary_reason_names_mode(self, tmp_path):
        target = _source_checkout_target(tmp_path)
        report = run_doctor_check(target)
        assert "source checkout" in report["primary_reason"].lower()

    def test_clean_checkout_info_explains_runtime_files(self, tmp_path):
        target = _source_checkout_target(tmp_path)
        report = run_doctor_check(target)
        info = " ".join(report.get("info", []))
        assert "settings.json" in info or "runtime" in info.lower()

    def test_missing_committed_surface_still_fails(self, tmp_path):
        # Source checkout WITH a committed-surface file deleted — this is
        # a real failure (source control should provide cc/COMMANDS.md).
        target = _source_checkout_target(tmp_path)
        (target / "cc" / "COMMANDS.md").unlink()
        report = run_doctor_check(target)
        assert report["status"] == "fail"
        assert any("COMMANDS.md" in f for f in report["failures"])


# ---------------------------------------------------------------------------
# Initialized mode still catches real drift
# ---------------------------------------------------------------------------


class TestInitializedDoctor:
    def test_after_init_runs_full_checks(self, tmp_path):
        target = _initialized_self_host(tmp_path)
        report = run_doctor_check(target)
        assert report["mode"] == REPO_MODE_INITIALIZED_SELF_HOST
        # Every standard check present. The count is deliberately NOT restated
        # here: this comment read "All 5 standard checks" above a six-name
        # tuple, which is the same off-by-count drift the tuple exists to
        # catch, sitting inside the pin. `docs/TROUBLESHOOTING.md`'s prose count
        # is derived from the payload by
        # tests/test_troubleshooting_enumerations.py::TestDoctorCheckRoster.
        for check in ("presence", "audit", "reflect", "recover", "diff", "self_host"):
            assert check in report["checks"]


# ---------------------------------------------------------------------------
# Explicit --mode override
# ---------------------------------------------------------------------------


class TestExplicitModeOverride:
    def test_explicit_source_checkout_on_clean_clone_via_cli(self, tmp_path):
        target = _source_checkout_target(tmp_path)
        result = subprocess.run(
            [sys.executable, "-m", "espalier.cli", "doctor",
             str(target), "--mode", "source-checkout"],
            capture_output=True, text=True, timeout=60, encoding="utf-8",
        )
        assert result.returncode == 0
        report = json.loads(result.stdout)
        assert report["mode"] == REPO_MODE_SOURCE_CHECKOUT

    def test_explicit_initialized_on_clean_clone_fails_loudly(self, tmp_path):
        # Forcing initialized mode on a source checkout exposes the missing
        # runtime files as the real failure they would be in that mode.
        target = _source_checkout_target(tmp_path)
        result = subprocess.run(
            [sys.executable, "-m", "espalier.cli", "doctor",
             str(target), "--mode", "initialized"],
            capture_output=True, text=True, timeout=60, encoding="utf-8",
        )
        assert result.returncode == 1, (
            f"forced initialized mode on a clean clone should fail; got rc={result.returncode}"
        )
        report = json.loads(result.stdout)
        # Primary reason names a missing runtime file
        primary = report["primary_reason"]
        assert ("settings.json" in primary
                or "reports/" in primary
                or "managed surface" in primary.lower())


# ---------------------------------------------------------------------------
# The fixture's own cleanliness (DEF-481)
# ---------------------------------------------------------------------------


def _files_under(root: Path) -> set[str]:
    """Every file or symlink below ``root`` except ``.git/``, never following links."""
    found: set[str] = set()
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d != ".git"]
        rel_dir = Path(dirpath).relative_to(root)
        for name in filenames:
            found.add((rel_dir / name).as_posix())
        for name in dirnames:
            if os.path.islink(os.path.join(dirpath, name)):
                found.add((rel_dir / name).as_posix())
    return found


class TestSourceCheckoutTargetIsClean:
    """The copy the classes above call clean is exactly what a fresh clone has.

    Checked against `git ls-files` in BOTH directions -- nothing rode in that
    a clone lacks, nothing a clone has was left out -- so it runs on every
    tree the fixture runs on and never skips. The two pins this replaces
    certified a hand-kept exclusion set and skipped wherever the live
    artifacts were absent, which was every CI checkout (DEF-481).
    """

    def test_the_copy_is_exactly_the_tracked_set(self, tmp_path):
        tracked = set(require_tracked_paths(REPO_ROOT, minimum=200, what="tracked files"))
        target = _source_checkout_target(tmp_path)
        copied = _files_under(target)
        residue = sorted(copied - tracked)
        missing = sorted(tracked - copied)
        assert residue == [], f"untracked residue in the clean copy: {residue[:10]}"
        assert missing == [], f"tracked files missing from the clean copy: {missing[:10]}"
