"""Portable fixtures for the Espalier host-agnostic test set.

Synthetic *_repo builders construct minimal projects in tmp_path from the
rows of _stack_trees.py; no fixture reads the harness source tree, and no
self-host fixtures are carried. Two autouse isolation fixtures keep runs
hermetic.

GENERATED by scripts/sync_selfcheck_tests.py — do not hand-edit; the
parity test reds on drift.
"""
from __future__ import annotations

import pytest

from _stack_trees import write_stack


@pytest.fixture(autouse=True)
def _isolate_maintenance_mode(monkeypatch):
    monkeypatch.delenv("ESPALIER_MAINTENANCE_MODE", raising=False)


@pytest.fixture(autouse=True)
def _isolate_audit_dir(monkeypatch, tmp_path):
    audit_tmp = tmp_path / "audit"
    audit_tmp.mkdir()
    monkeypatch.setenv("ESPALIER_AUDIT_DIR", str(audit_tmp))


@pytest.fixture
def python_repo(tmp_path):
    """Minimal Python project with known patterns. The `python` row of tests/_stack_trees.py."""
    write_stack(tmp_path, "python")
    # cmd_init pre-flight requires .git/. Mark as a git directory
    # (empty marker is sufficient — pre-flight only checks existence).
    (tmp_path / ".git").mkdir(exist_ok=True)
    return tmp_path


@pytest.fixture
def ml_repo(tmp_path):
    """Minimal ML project. The `ml` row of tests/_stack_trees.py."""
    write_stack(tmp_path, "ml")
    (tmp_path / ".git").mkdir(exist_ok=True)  # cmd_init pre-flight.
    return tmp_path


@pytest.fixture
def node_repo(tmp_path):
    """Minimal Node.js project. The `node` row of tests/_stack_trees.py."""
    write_stack(tmp_path, "node")
    (tmp_path / ".git").mkdir(exist_ok=True)  # cmd_init pre-flight.
    return tmp_path


@pytest.fixture
def typescript_repo(tmp_path):
    """Minimal TypeScript project (non-Python consumer fixture). The `typescript` row of tests/_stack_trees.py."""
    write_stack(tmp_path, "typescript")
    (tmp_path / ".git").mkdir(exist_ok=True)  # cmd_init pre-flight.
    return tmp_path


@pytest.fixture
def go_repo(tmp_path):
    """Minimal Go project (non-Python consumer fixture). The `go` row of tests/_stack_trees.py."""
    write_stack(tmp_path, "go")
    (tmp_path / ".git").mkdir(exist_ok=True)  # cmd_init pre-flight.
    return tmp_path


@pytest.fixture
def polyglot_repo(tmp_path):
    """Python-primary + TypeScript-secondary polyglot fixture. The `polyglot` row of tests/_stack_trees.py."""
    write_stack(tmp_path, "polyglot")
    (tmp_path / ".git").mkdir(exist_ok=True)  # cmd_init pre-flight.
    return tmp_path
