"""Portable fixtures for the Espalier host-agnostic test set.

Synthetic *_repo builders construct minimal projects in tmp_path; no
fixture reads the harness source tree, and no self-host fixtures are
carried. Two autouse isolation fixtures keep runs hermetic.

GENERATED by scripts/sync_selfcheck_tests.py — do not hand-edit; the
parity test reds on drift.
"""
from __future__ import annotations

import pytest


@pytest.fixture(autouse=True)
def _isolate_maintenance_mode(monkeypatch):
    monkeypatch.delenv("ESPALIER_MAINTENANCE_MODE", raising=False)


@pytest.fixture(autouse=True)
def _isolate_audit_dir(monkeypatch, tmp_path):
    audit_tmp = tmp_path / "audit"
    audit_tmp.mkdir()
    monkeypatch.setenv("ESPALIER_AUDIT_DIR", str(audit_tmp))


@pytest.fixture
def python_repo(tmp_path):
    """Minimal Python project with known patterns."""
    (tmp_path / "src").mkdir()
    (tmp_path / "tests").mkdir()
    (tmp_path / "app.py").write_text(
        'from fastapi import FastAPI\n'
        'app = FastAPI()\n'
        '@app.get("/health")\n'
        'def health():\n'
        '    return {"status": "ok"}\n'
        'def helper():\n'
        '    try:\n'
        '        x = open("/tmp/foo")\n'
        '    except:\n'
        '        pass\n'
        '    print("debug")\n',
        encoding="utf-8",
    )
    (tmp_path / "src" / "utils.py").write_text(
        'def _cache_load(): pass\n'
        'def _cache_save(): pass\n'
        'def _cache_invalidate(): pass\n'
        'def _cache_warm(): pass\n'
        'def unrelated(): pass\n',
        encoding="utf-8",
    )
    (tmp_path / "tests" / "test_health.py").write_text("def test_health(): assert True\n", encoding="utf-8")
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "test-api"\n'
        '[tool.pytest.ini_options]\ntestpaths = ["tests"]\n'
        '[tool.ruff]\nline-length = 100\n',
        encoding="utf-8",
    )
    (tmp_path / "README.md").write_text("# Test API\nA FastAPI service.\n", encoding="utf-8")
    # cmd_init pre-flight requires .git/. Mark as a git directory
    # (empty marker is sufficient — pre-flight only checks existence).
    (tmp_path / ".git").mkdir(exist_ok=True)
    return tmp_path


@pytest.fixture
def ml_repo(tmp_path):
    """Minimal ML project."""
    (tmp_path / "src").mkdir()
    (tmp_path / "tests").mkdir()
    (tmp_path / "train.py").write_text(
        'import torch\n'
        'model = torch.nn.Linear(10, 1)\n'
        'def train():\n'
        '    model.cuda()\n'
        '    print("training")\n',
        encoding="utf-8",
    )
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "ml-proj"\ndependencies = ["torch", "transformers"]\n'
        '[tool.pytest.ini_options]\ntestpaths = ["tests"]\n',
        encoding="utf-8",
    )
    (tmp_path / "tests" / "test_train.py").write_text("def test_train(): assert True\n", encoding="utf-8")
    (tmp_path / "README.md").write_text("# ML Project\n", encoding="utf-8")
    (tmp_path / ".git").mkdir(exist_ok=True)  # cmd_init pre-flight.
    return tmp_path


@pytest.fixture
def node_repo(tmp_path):
    """Minimal Node.js project."""
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "index.js").write_text("console.log('hello');\n", encoding="utf-8")
    (tmp_path / "package.json").write_text(
        '{"name":"test-app","scripts":{"test":"jest","build":"next build","dev":"next dev"}}\n',
        encoding="utf-8",
    )
    (tmp_path / "README.md").write_text("# Node App\n", encoding="utf-8")
    (tmp_path / ".git").mkdir(exist_ok=True)  # cmd_init pre-flight.
    return tmp_path


@pytest.fixture
def typescript_repo(tmp_path):
    """Minimal TypeScript project (non-Python consumer fixture)."""
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "index.ts").write_text(
        "export function greet(name: string): string {\n"
        "  return `hello, ${name}`;\n"
        "}\n",
        encoding="utf-8",
    )
    (tmp_path / "src" / "app.tsx").write_text(
        "export const App = () => null;\n",
        encoding="utf-8",
    )
    (tmp_path / "tests").mkdir()
    (tmp_path / "tests" / "index.test.ts").write_text(
        "import { greet } from '../src/index';\n"
        "test('greet', () => { expect(greet('w')).toBe('hello, w'); });\n",
        encoding="utf-8",
    )
    (tmp_path / "package.json").write_text(
        '{"name":"ts-app","scripts":{"test":"jest","build":"tsc"}}\n',
        encoding="utf-8",
    )
    (tmp_path / "tsconfig.json").write_text(
        '{"compilerOptions":{"target":"ES2020","module":"commonjs","strict":true}}\n',
        encoding="utf-8",
    )
    (tmp_path / "README.md").write_text("# TS App\n", encoding="utf-8")
    (tmp_path / ".git").mkdir(exist_ok=True)  # cmd_init pre-flight.
    return tmp_path


@pytest.fixture
def go_repo(tmp_path):
    """Minimal Go project (non-Python consumer fixture)."""
    (tmp_path / "go.mod").write_text(
        "module example.com/demo\n\ngo 1.21\n",
        encoding="utf-8",
    )
    (tmp_path / "cmd").mkdir()
    (tmp_path / "cmd" / "main.go").write_text(
        'package main\n\nimport "fmt"\n\nfunc main() { fmt.Println("hi") }\n',
        encoding="utf-8",
    )
    (tmp_path / "internal").mkdir()
    (tmp_path / "internal" / "foo").mkdir()
    (tmp_path / "internal" / "foo" / "foo.go").write_text(
        'package foo\n\nfunc Greet() string { return "hello" }\n',
        encoding="utf-8",
    )
    (tmp_path / "internal" / "foo" / "foo_test.go").write_text(
        'package foo\n\nimport "testing"\n\n'
        'func TestGreet(t *testing.T) { if Greet() != "hello" { t.Fail() } }\n',
        encoding="utf-8",
    )
    (tmp_path / "README.md").write_text("# Go App\n", encoding="utf-8")
    (tmp_path / ".git").mkdir(exist_ok=True)  # cmd_init pre-flight.
    return tmp_path


@pytest.fixture
def polyglot_repo(tmp_path):
    """Python-primary + TypeScript-secondary polyglot fixture."""
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "poly"\n'
        '[tool.pytest.ini_options]\ntestpaths = ["tests"]\n',
        encoding="utf-8",
    )
    (tmp_path / "src").mkdir()
    for name in ("a", "b", "c", "d", "e"):
        (tmp_path / "src" / f"{name}.py").write_text(
            f"def {name}(): return {name!r}\n", encoding="utf-8",
        )
    (tmp_path / "tests").mkdir()
    (tmp_path / "tests" / "test_a.py").write_text(
        "from src.a import a\n\ndef test_a(): assert a() == 'a'\n",
        encoding="utf-8",
    )
    # TypeScript secondary: fewer files than Python so primary stays python.
    (tmp_path / "web").mkdir()
    (tmp_path / "web" / "index.ts").write_text(
        "export const v = 1;\n", encoding="utf-8",
    )
    (tmp_path / "package.json").write_text(
        '{"name":"poly-web","scripts":{"build":"tsc"}}\n',
        encoding="utf-8",
    )
    (tmp_path / "README.md").write_text("# Polyglot\n", encoding="utf-8")
    (tmp_path / ".git").mkdir(exist_ok=True)  # cmd_init pre-flight.
    return tmp_path
