#!/usr/bin/env python3
"""Sync ``espalier/_vendor/selfcheck_tests/`` from the canonical ``tests/`` subset.

The curated host-agnostic engine-integrity tests have their canonical home in
``tests/`` (dev pytest collects them; pyproject ``testpaths`` is ``["tests"]``).
A MIRROR lives inside the engine package at ``espalier/_vendor/selfcheck_tests/``
so it travels with the engine — ``fuse`` overlays all of ``espalier/`` and the
wheel ships the package-data glob — and ``espalier selfcheck`` can run it against
the INSTALLED location. ``tests/test_selfcheck_tests_parity.py`` reds if the two
drift from the curation rule.

Two flavours of mirrored file:

* ``BYTE_MIRRORED`` — copied byte-for-byte (parity = byte-identity, exactly like
  ``_vendor/cc``). Each imports only ``espalier`` + stdlib and uses only synthetic
  ``tmp_path`` fixtures.
* ``TRANSFORMED`` — produced by a DETERMINISTIC curated transform (parity = the
  transform re-applied to current source). ``conftest.py`` keeps only the portable
  fixtures (the self-host fixtures that read the source tree are dropped);
  ``test_scanners.py`` drops the two source-dir-reading classes that cannot run
  beside an installed wheel; ``pytest.ini`` is authored.

Run this after editing any curated ``tests/`` source so the mirror stays in
lockstep::

    python scripts/sync_selfcheck_tests.py            # write the mirror
    python scripts/sync_selfcheck_tests.py --check    # verify only; exit 1 on drift

Stdlib-only: copies/derives the curated subset into the mirror and prunes any
mirrored file no longer in the curation rule, so the bijection holds both ways.
``--check`` re-derives the expected bytes in memory and diffs against disk
without writing (the same bijection the parity test enforces, as a CLI).
"""
from __future__ import annotations

import argparse
import ast
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "tests"
MIRROR = REPO_ROOT / "espalier" / "_vendor" / "selfcheck_tests"

# Copied byte-for-byte (parity = byte-identity).
BYTE_MIRRORED: tuple[str, ...] = (
    "test_engine_imports.py",
    "test_fingerprint.py",
    "test_analyze.py",
    "test_models.py",
    "test_config.py",
    "test_test_loosening_skip_precision.py",
)
# Produced by a curated transform (parity = transform-applied, not bytes).
TRANSFORMED: tuple[str, ...] = ("conftest.py", "pytest.ini", "test_scanners.py")

PYTEST_INI = """\
[pytest]
addopts = -p no:cacheprovider
filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning
"""

# Authored header for the mirror conftest: the module docstring + the two autouse
# isolation fixtures, written verbatim (no provenance, no source-tree reads). The
# six synthetic ``*_repo`` builders are appended from source by the transform.
_CONFTEST_HEADER = '''\
"""Portable fixtures for the Espalier host-agnostic test set.

Synthetic *_repo builders construct minimal projects in tmp_path; no
fixture reads the harness source tree, and no self-host fixtures are
carried. Two autouse isolation fixtures keep runs hermetic.

GENERATED by scripts/sync_selfcheck_tests.py — do not hand-edit; the
parity test reds on drift.
"""
from __future__ import annotations

import pytest


@pytest.fixture(autouse=True)
def _isolate_maintenance_mode(monkeypatch):
    monkeypatch.delenv("ESPALIER_MAINTENANCE_MODE", raising=False)


@pytest.fixture(autouse=True)
def _isolate_audit_dir(monkeypatch, tmp_path):
    audit_tmp = tmp_path / "audit"
    audit_tmp.mkdir()
    monkeypatch.setenv("ESPALIER_AUDIT_DIR", str(audit_tmp))
'''

# The synthetic builders the curated subset actually uses (verified by grepping
# fixture params across the mirrored files). The self-host fixtures
# (``harness_repo`` / ``initialized_repo_root``) and unused builders are dropped.
_PORTABLE_FIXTURES: tuple[str, ...] = (
    "python_repo",
    "ml_repo",
    "node_repo",
    "typescript_repo",
    "go_repo",
    "polyglot_repo",
)

# The two source-dir-reading classes in test_scanners.py — they resolve the
# source scanner directory off disk and cannot run beside an installed mirror.
_DROP_SCANNER_CLASSES: frozenset[str] = frozenset(
    {"TestScannerSelfContainment", "TestScannerExemptPrefixesParity"}
)


def _fixture_blocks(src_text: str, names: set[str]) -> dict[str, str]:
    """Map fixture name -> its verbatim source block (decorator line .. end)."""
    tree = ast.parse(src_text)
    lines = src_text.splitlines()
    blocks: dict[str, str] = {}
    for node in tree.body:
        if (
            isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
            and node.name in names
        ):
            start = node.decorator_list[0].lineno if node.decorator_list else node.lineno
            blocks[node.name] = "\n".join(lines[start - 1 : node.end_lineno])
    return blocks


def _transform_conftest(src_text: str) -> str:
    """Author the mirror conftest: the fixed header (docstring + two autouse
    fixtures) followed by the six portable ``*_repo`` builders extracted verbatim
    from the source conftest. Deterministic so the parity test can re-derive it."""
    blocks = _fixture_blocks(src_text, set(_PORTABLE_FIXTURES))
    missing = [name for name in _PORTABLE_FIXTURES if name not in blocks]
    if missing:
        raise SystemExit(
            f"sync_selfcheck_tests: source conftest missing fixtures: {missing}"
        )
    out = _CONFTEST_HEADER.rstrip("\n") + "\n"
    for name in _PORTABLE_FIXTURES:
        out += "\n\n" + blocks[name] + "\n"
    return out


def _transform_test_scanners(src_text: str) -> str:
    """Drop the two source-dir-reading classes (with their leading ``# pins:``
    comment) and the now-unused ``from pathlib import Path`` import; keep
    TestScanners / TestGodfilesThreshold / TestTestLoosening. Deterministic so the
    parity test can re-derive it."""
    tree = ast.parse(src_text)
    lines = src_text.splitlines()
    drop: set[int] = set()

    # 1. The now-unused ``from pathlib import Path`` import (+ one trailing blank).
    for node in tree.body:
        if (
            isinstance(node, ast.ImportFrom)
            and node.module == "pathlib"
            and any(alias.name == "Path" for alias in node.names)
        ):
            i = node.lineno - 1
            drop.add(i)
            if i + 1 < len(lines) and not lines[i + 1].strip():
                drop.add(i + 1)

    # 2. The span of the two source-dir-reading classes + their leading comment.
    top = list(tree.body)
    dropped = [
        n
        for n in top
        if isinstance(n, ast.ClassDef) and n.name in _DROP_SCANNER_CLASSES
    ]
    if len(dropped) != len(_DROP_SCANNER_CLASSES):
        raise SystemExit(
            "sync_selfcheck_tests: expected the two source-dir-reading classes in "
            f"test_scanners.py; found {sorted(n.name for n in dropped)}"
        )
    span_end = max(n.end_lineno or n.lineno for n in dropped)
    first_lineno = min(n.lineno for n in dropped)
    # Absorb the contiguous comment block (`# pins:`) directly above the class.
    start = first_lineno - 1
    while start - 1 >= 0 and lines[start - 1].lstrip().startswith("#"):
        start -= 1
    # End just before the first kept top-level node after the dropped span.
    after = [n.lineno for n in top if n.lineno > span_end]
    if not after:
        raise SystemExit(
            "sync_selfcheck_tests: no kept class follows the dropped span in "
            "test_scanners.py"
        )
    end_excl = min(after) - 1  # 0-based exclusive: the kept class's line
    for i in range(start, end_excl):
        drop.add(i)

    kept = [line for i, line in enumerate(lines) if i not in drop]
    return "\n".join(kept) + "\n"


def _mirror_files() -> set[str]:
    """Repo-relative names under MIRROR, excluding ``__pycache__``."""
    if not MIRROR.exists():
        return set()
    return {
        p.relative_to(MIRROR).as_posix()
        for p in MIRROR.rglob("*")
        if p.is_file() and "__pycache__" not in p.parts
    }


def _planned() -> dict[str, bytes]:
    """The exact bytes each mirror file should contain — the single source of
    truth shared by ``sync`` (write) and ``check`` (verify without writing), so
    the two can never disagree about what "in sync" means."""
    planned: dict[str, bytes] = {}
    for name in BYTE_MIRRORED:
        planned[name] = (SRC / name).read_bytes()
    planned["conftest.py"] = _transform_conftest(
        (SRC / "conftest.py").read_text(encoding="utf-8")
    ).encode("utf-8")
    planned["test_scanners.py"] = _transform_test_scanners(
        (SRC / "test_scanners.py").read_text(encoding="utf-8")
    ).encode("utf-8")
    planned["pytest.ini"] = PYTEST_INI.encode("utf-8")
    return planned


def sync() -> tuple[int, int]:
    """Generate the mirror from the curated ``tests/`` subset. Returns
    ``(written, pruned)``."""
    MIRROR.mkdir(parents=True, exist_ok=True)
    planned = _planned()
    for name, data in planned.items():
        (MIRROR / name).write_bytes(data)
    orphans = sorted(_mirror_files() - set(planned))
    for name in orphans:
        (MIRROR / name).unlink()
    return len(planned), len(orphans)


def check() -> list[str]:
    """Return a list of drift descriptions (empty == mirror in sync). Pure read,
    never writes — so an operator or a preflight step can verify drift without a
    full pytest run. The authoritative gate stays
    tests/test_selfcheck_tests_parity.py; this is the same bijection as a CLI."""
    planned = _planned()
    on_disk = _mirror_files()
    drift: list[str] = []
    for name in sorted(set(planned) - on_disk):
        drift.append(f"missing from mirror: {name}")
    for name in sorted(on_disk - set(planned)):
        drift.append(f"orphan in mirror (not in curation rule): {name}")
    for name in sorted(set(planned) & on_disk):
        if (MIRROR / name).read_bytes() != planned[name]:
            drift.append(f"drifted from curated source: {name}")
    return drift


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Sync (or --check) the espalier/_vendor/selfcheck_tests mirror "
            "from the curated tests/ subset."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the mirror matches the curated source WITHOUT writing; "
        "exit 1 on drift (for CI / preflight).",
    )
    args = parser.parse_args(argv)

    if args.check:
        drift = check()
        if drift:
            print("selfcheck mirror DRIFT (run scripts/sync_selfcheck_tests.py to fix):")
            for line in drift:
                print(f"  - {line}")
            return 1
        print("selfcheck mirror is in sync with tests/")
        return 0

    written, pruned = sync()
    print(
        f"synced espalier/_vendor/selfcheck_tests <- tests: "
        f"{written} written, {pruned} pruned"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
