"""Hook timing constants — standalone copy for tools/cc/hooks scripts.

This file is a copy of espalier/hook_contract.py kept in sync by
tests/test_hook_contracts.py. Hook scripts in tools/cc/hooks/ cannot
import from espalier/ (isolation rule), so they import from this copy.

Do not edit this file directly — edit espalier/hook_contract.py and
update this copy to match.
"""
from __future__ import annotations

STOP_OUTER_TIMEOUT: int = 90
STOP_INNER_BUDGET: int = 60
STOP_SAFETY_MARGIN: int = 15
