"""Single source of truth for the espalier:managed marker contract.

Espalier-Harness owns ("manages") files it deploys. The marker is the
ownership signal that lets ``espalier init`` distinguish files it
generated (safe to regenerate) from files a user authored (must be
preserved). The marker also lets cleanup, audit, and doctor identify
managed surface without reaching into deploy logic.

Public contract::

    if target does not exist:
        write file with managed marker
    if target exists and has_managed_marker(content):
        regenerate (overwrite with the new managed copy)
    if target exists and not has_managed_marker(content):
        preserve and report as a skipped user file

Marker placement rules:
- ``.md`` with YAML frontmatter → ``apply_marker_to_md`` inserts the
  HTML comment AFTER the closing ``---`` so frontmatter parsers (Claude
  Code agent loader, GitHub renderer, MkDocs) see a valid frontmatter
  block at the top of the file.
- ``.md`` without frontmatter → marker prepended at the top.
- ``.toml`` / ``.txt`` / ``.py`` → ``apply_marker_to_text`` prepends a
  ``# espalier:managed`` line (or after a ``#!`` shebang).
- ``.cmd`` (the Windows statusline shim) → ``apply_marker_to_batch`` inserts
  a ``:: espalier:managed`` line after a leading ``@echo off``: to cmd.exe a
  ``#`` line is a command, and a line before the echo-off is echoed to stdout,
  which is the statusline's channel.
- ``.json`` (settings.json) → no inline marker; the JSON sentinel key
  ``_espalier_managed`` (boolean ``true``) lives at the top level.

Centralizing these constants closes the duplication that previously
lived across handoff.py, managed_paths.py, proofs.py, render_surface.py,
and inline string literals in cli.py.
"""
from __future__ import annotations

import re
import unicodedata
from pathlib import Path

__all__ = [
    "MANAGED_MARKER",
    "MARKER_HTML_COMMENT_RICH",
    "MARKER_HTML_COMMENT_SHORT",
    "MARKER_HASH_COMMENT",
    "MARKER_BATCH_COMMENT",
    "JSON_SENTINEL_KEY",
    "MARKER_SCAN_BYTES",
    "has_managed_marker",
    "file_carries_marker",
    "strip_managed_marker_line",
    "apply_marker_to_md",
    "apply_marker_to_text",
    "apply_marker_to_batch",
    "find_confusable_markers",
    "SEED_STAMP_TOKEN",
    "SEED_STAMP_RE",
    "SEED_STAMP_SCAN_BYTES",
    "seed_stamp_digest",
    "has_seed_stamp",
    "seed_is_untouched",
    "path_has_seed_stamp",
]


# ── Constants ──────────────────────────────────────────────────────────────

MANAGED_MARKER = "espalier:managed"
"""Bare marker token. Substring of every managed-marker comment form."""

MARKER_HTML_COMMENT_RICH = (
    "<!-- espalier:managed - regenerated by `espalier init`; "
    "edit at your own risk -->"
)
"""Full marker line for files deployed by ``espalier init``."""

MARKER_HTML_COMMENT_SHORT = "<!-- espalier:managed -->"
"""Compact marker for rendered cc/ surface docs and other generators
that don't need the regeneration warning."""

MARKER_HASH_COMMENT = "# espalier:managed"
"""Marker form for files where ``#`` is the comment character
(``.toml``, ``.txt``, ``.py``)."""

MARKER_BATCH_COMMENT = ":: espalier:managed"
"""Marker form for a batch file (the Windows statusline shim, DEF-729):
``::`` is a comment to cmd.exe, ``#`` is a command."""

JSON_SENTINEL_KEY = "_espalier_managed"
"""Top-level boolean key in ``settings.json`` that signals the file is
managed. Written by ``espalier init`` (``cli.py``) when it stamps the
rendered ``settings.json.new``; read by ``cleanup.py``'s orphan-sweep
and by the ``harness-config-advisor`` agent asset to distinguish
harness-deployed configs from user-authored ones. (Not ``config_guard``
— that hook is stdlib-only and cannot import espalier; it keys on
``policy_settings``, a different contract.)"""

MARKER_SCAN_BYTES = 600
"""Default scan window for ``has_managed_marker`` on files without YAML
frontmatter. Files with frontmatter automatically scan past the close;
see ``has_managed_marker``.

The scan window applies to a *line-anchored* regex search rather than a
bare substring scan. A YAML scalar or prose paragraph referencing
``espalier:managed`` as text no longer triggers recognition; only
``# espalier:managed``, ``<!-- espalier:managed`` or the batch form
``:: espalier:managed`` appearing at the start of a comment line counts as
an ownership signal.
"""

POST_FRONTMATTER_SCAN_PADDING = 200
"""Extra characters scanned after the YAML frontmatter close so a marker
placed immediately past the closing ``---`` (the placement for files
with frontmatter) is reliably detected without scanning the full body."""


# ── Recognition ────────────────────────────────────────────────────────────


_MARKER_LINE_RE = re.compile(
    r"(?m)^[ \t]*(?:#|<!--|::)[ \t]*espalier:managed\b",
    re.ASCII,
)
"""Anchored marker pattern.

Matches the marker only when it appears at the start of a comment line:
``# espalier:managed``, ``<!-- espalier:managed`` or the batch form
``:: espalier:managed`` (with optional trailing text). Leading ASCII
whitespace (space, tab) is tolerated. ``tools/cc/sister_site_probe.py``
carries an inline mirror of this pattern (tools/cc has zero espalier
imports); ``tests/test_sister_site_probe_unit.py`` pins the two equal.

The ``re.ASCII`` flag is load-bearing: without it, ``\\s`` and ``\\b``
take Unicode semantics, which would let zero-width-space (U+200B) or
no-break-space (U+00A0) act as leading whitespace and slip a forgery
through. ``[ \\t]*`` makes the leading-whitespace class literal ASCII
and ``re.ASCII`` pins ``\\b`` to ASCII word boundaries.

Does NOT match: substring appearances inside YAML scalars, JSON
string values, prose paragraphs, or other descriptive contexts. Those
are the BC-026 forgery class — see ``bench/corpus/BC-026-marker-substring-forgery.json``.
"""


def has_managed_marker(content: str, *, scan_chars: int = MARKER_SCAN_BYTES) -> bool:
    """Return True if ``content`` carries the managed marker as an
    anchored comment line near the top.

    Recognition is anchored to ``#`` or ``<!--`` at the start of a
    comment line via ``_MARKER_LINE_RE`` so a YAML ``description``
    referencing the marker as text cannot make a hostile asset
    overwritable.

    Default-ignorable strip: a leading sequence of Unicode
    Format / Control / Surrogate / Unassigned codepoints (BOM,
    ZWSP, ZWJ, LRM, WORD JOINER, bidi controls, tag chars, etc.)
    would otherwise displace the regex's ``^`` anchor and cause an
    existing managed file to be silently demoted to user-modified.
    The function strips any such prefix before scanning. Categories
    Cf (Format) and Cc (Control) cover all current
    defaults-ignorables; Cs (Surrogate) and Cn (Unassigned) are
    defensive (should not appear in valid UTF-8); Zl (Line Separator)
    and Zp (Paragraph Separator) cover leading line/paragraph
    separators. Leading ASCII
    tab is also Cc and gets stripped, which is benign — the regex
    ``[ \\t]*`` would have consumed it anyway.

    Scan window:
    - **No YAML frontmatter:** first ``scan_chars`` characters.
    - **YAML frontmatter present:** the larger of ``scan_chars`` and the
      offset of the closing ``---`` plus ``POST_FRONTMATTER_SCAN_PADDING``.
      This guarantees a marker placed directly after a long frontmatter
      block (e.g., agent file with a multi-line ``description:`` scalar)
      is found without paying for a full-file scan.
    """
    i = 0
    while i < len(content):
        if unicodedata.category(content[i]) not in {
            "Cf", "Cc", "Cs", "Cn", "Zl", "Zp",
        }:
            break
        i += 1
    if i > 0:
        content = content[i:]
    end = _frontmatter_end_index(content)
    if end >= 0:
        scan = max(scan_chars, end + POST_FRONTMATTER_SCAN_PADDING)
    else:
        scan = scan_chars
    return _MARKER_LINE_RE.search(content[:scan]) is not None


def file_carries_marker(path: Path) -> bool:
    """True if the file at ``path`` carries the managed marker.

    Single owner for the ``_is_managed`` / ``_file_is_managed`` pair that
    proofs.py and cleanup.py previously hand-rolled with drifted read
    strategies. A missing path, a non-regular file (directory, FIFO,
    device), or an unreadable file all return False — refuse to treat
    anything we cannot positively read as a managed regular file as ours.
    The ``exists()``/``is_file()`` guard is the strict superset of the two
    prior copies: it hardens cleanup's delete loop against a
    between-check unlink or a non-file target. Reads with replacement
    decoding so a partially-binary file cannot raise.
    """
    if not path.exists() or not path.is_file():
        return False
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return has_managed_marker(text)


def strip_managed_marker_line(lines: list[str]) -> list[str]:
    """Drop a leading managed-marker comment line if present.

    The report loaders (handoff/reflection/diffing/proofs/
    cognitive_blueprint) each hand-rolled
    ``if lines and MANAGED_MARKER in lines[0]: lines = lines[1:]``
    against the bare marker token. This routes that test through MANAGED_MARKER
    so the marker token has one owner. Substring (not equality) match is
    intentional — the marker ships as ``# espalier:managed`` / ``<!-- ... -->``
    comment forms, so the line wraps the token.
    """
    if lines and MANAGED_MARKER in lines[0]:
        return lines[1:]
    return lines


def _legacy_substring_match(
    content: str, *, scan_chars: int = MARKER_SCAN_BYTES,
) -> bool:
    """DEPRECATED — TEST-ONLY: pre-fix substring recognition.

    Production-dead: no espalier/ runtime caller. Retained solely as the
    BC-026 regression baseline for the single migration test
    (tests/test_managed_markers.py::TestLegacySubstringHelperIsolated) that
    asserts the public ``has_managed_marker`` API no longer routes through
    this code path. The substring approach was vulnerable to BC-026 (a YAML
    ``description`` field referencing the marker as text was enough to make a
    hostile asset overwritable). Do NOT call from new code; use
    ``has_managed_marker`` instead.
    """
    end = _frontmatter_end_index(content)
    if end >= 0:
        scan = max(scan_chars, end + POST_FRONTMATTER_SCAN_PADDING)
    else:
        scan = scan_chars
    return MANAGED_MARKER in content[:scan]


# ── Confusable-marker loud-warning surface ────────────────────────────────


# Patterns that visually resemble the canonical marker but deliberately
# fail the anchored regex (the file is still treated as not-managed,
# which is the secure outcome). These patterns surface a "you may have
# intended this but the engine won't recognise it" warning so a
# maintainer doesn't merge a PR with a confusable marker that would
# render the asset silently not-managed. The patterns intentionally do
# NOT use ``re.ASCII`` because Unicode codepoints are what we want to
# match.
_CONFUSABLE_PATTERNS = (
    # Cyrillic confusables anywhere in the marker phrase. Each ASCII
    # position permits its ASCII counterpart OR the visually-identical
    # Cyrillic codepoint, so a mid-word Cyrillic 'a' (U+0430) in
    # 'espalier:managed' is caught. Codepoints are written as \uXXXX
    # escapes (not literal Cyrillic) so the source distinguishes Latin
    # from Cyrillic positions at a glance.
    re.compile(
        # e / E vs Cyrillic e (U+0435) / E (U+0415)
        "[Ee\u0435\u0415]"
        # s / S vs Cyrillic s (U+0455) / S (U+0405)
        "[Ss\u0455\u0405]"
        # p / P vs Cyrillic p (U+0440) / P (U+0420)
        "[Pp\u0440\u0420]"
        # a / A vs Cyrillic a (U+0430) / A (U+0410)
        "[Aa\u0430\u0410]"
        # l vs Cyrillic palochka (U+04CF) -- rare
        "[Ll\u04cf]"
        # i / I vs Cyrillic i (U+0456) / I (U+0406)
        "[Ii\u0456\u0406]"
        "[Ee\u0435\u0415]"
        # r unambiguous in the basic Cyrillic block
        "[Rr]"
        ":"
        # m unambiguous
        "[Mm]"
        "[Aa\u0430\u0410]"
        # n unambiguous
        "[Nn]"
        "[Aa\u0430\u0410]"
        # g unambiguous (script g U+0261 is IPA, very rare)
        "[Gg]"
        "[Ee\u0435\u0415]"
        # d unambiguous
        "[Dd]"
    ),
    # HTML-entity preceding the marker phrase. Any decimal/hex entity
    # in any position could substitute for any letter; this pattern
    # catches the common forgery shape: an entity-encoded character
    # followed by the rest of the phrase.
    re.compile(r"&#x?[0-9a-fA-F]+;[a-zA-Z]*palier:managed", re.IGNORECASE),
)


def find_confusable_markers(content: str) -> list[tuple[str, int]]:
    """Return ``(matched-text, line-number)`` tuples for marker-shaped
    substrings that fail anchor-match.

    Empty when the file uses only canonical markers (or no markers at
    all). The list surfaces a maintainer-review warning: a PR diff
    containing one of these would visually look like a real marker but
    would render the asset not-managed at recognition time — a silent
    disable. Used by ``tests/test_managed_markers.py::TestConfusableDetection``
    as a contract test over ``espalier/assets/**``.

    Output is deduplicated and sorted for deterministic ordering.
    """
    out: list[tuple[str, int]] = []
    for pattern in _CONFUSABLE_PATTERNS:
        for m in pattern.finditer(content):
            text = m.group(0)
            # Skip the canonical ASCII marker phrase — the permissive
            # Cyrillic character classes also match plain ASCII, so a
            # canonical ``espalier:managed`` would otherwise be flagged
            # as a confusable of itself. A confusable must contain at
            # least one non-ASCII codepoint OR be a case variant
            # (the canonical phrase is lowercase ASCII).
            if text.isascii() and text == MANAGED_MARKER:
                continue
            line_no = content[: m.start()].count("\n") + 1
            out.append((text, line_no))
    return sorted(set(out))


# ── Insertion ──────────────────────────────────────────────────────────────


def _has_yaml_frontmatter(content: str) -> bool:
    """A file has YAML frontmatter when it opens with ``---\\n`` and
    contains a closing ``\\n---\\n`` (or ``\\n---`` at end-of-file)."""
    if not content.startswith("---\n"):
        return False
    return _frontmatter_end_index(content) >= 0


def _frontmatter_end_index(content: str) -> int:
    """Return the index immediately past the closing frontmatter delimiter,
    or -1 if the file has no opening ``---\\n`` or no closing delimiter.

    Handles both ``\\n---\\n`` (delimiter followed by body) and ``\\n---``
    at end-of-file (delimiter at file end with no trailing newline).
    """
    if not content.startswith("---\n"):
        return -1
    # Search from index 3 — the newline that ENDS the opening `---` — not 4.
    # For an EMPTY frontmatter (`---\n---\n`) the closing `\n---\n` begins at
    # index 3, so starting at 4 skipped past it and the function wrongly
    # reported "no frontmatter"; the caller then PREPENDED the marker above
    # line 1 and invalidated the YAML. Index 3 cannot produce a false positive
    # on a non-empty block: content[3] is that same opening newline, and a
    # `\n---\n` match there requires the very next line to be the closing
    # delimiter, which is precisely the empty-frontmatter case.
    closing_idx = content.find("\n---\n", 3)
    if closing_idx >= 0:
        return closing_idx + len("\n---\n")
    if content.endswith("\n---"):
        return len(content)
    return -1


def apply_marker_to_md(
    content: str,
    *,
    comment: str = MARKER_HTML_COMMENT_RICH,
) -> str:
    """Return ``content`` with the managed marker inserted, frontmatter-aware.

    - Already marked: returned unchanged.
    - Has YAML frontmatter: marker line inserted directly after the
      closing ``---`` delimiter so frontmatter remains valid.
    - No frontmatter: marker line prepended at the top.

    The chosen ``comment`` (full or short) is the operator-visible line.
    """
    if has_managed_marker(content):
        return content
    if _has_yaml_frontmatter(content):
        end = _frontmatter_end_index(content)
        head = content[:end]
        tail = content[end:]
        # A frontmatter whose closing delimiter sits at EOF with no trailing
        # newline (`---\n---`) leaves `head` ending in `---`, so appending the
        # marker GLUES it onto the delimiter line and breaks the block. The
        # index is already correct there — len(content) is the honest answer for
        # "frontmatter ends at EOF" — so the newline belongs here, in the
        # inserter, not in the index contract.
        if not head.endswith("\n"):
            head += "\n"
        # Ensure exactly one blank line between marker and body.
        if not tail.startswith("\n"):
            tail = "\n" + tail
        return head + comment + tail
    # No frontmatter — prepend at top, separated from body by a newline.
    if not content.startswith("\n") and not content.startswith(comment):
        return comment + "\n" + content
    return comment + content


def apply_marker_to_text(content: str) -> str:
    """Return ``content`` with the ``# espalier:managed`` line prepended.

    Preserves a leading shebang (``#!``) by inserting the marker on the
    line immediately after it. Idempotent: already-marked content is
    returned unchanged.
    """
    if has_managed_marker(content):
        return content
    if content.startswith("#!"):
        first, _, rest = content.partition("\n")
        return first + "\n" + MARKER_HASH_COMMENT + "\n" + rest
    return MARKER_HASH_COMMENT + "\n" + content


def apply_marker_to_batch(content: str) -> str:
    """Return ``content`` with the ``:: espalier:managed`` line inserted.

    A batch file's first line is ``@echo off``; every line before it is
    echoed to stdout as cmd.exe runs it, and stdout is the statusline. So
    the marker goes on the line AFTER a leading ``@echo off`` (matched
    case-insensitively, as cmd.exe reads it), and at the top only when the
    file has none. Idempotent: already-marked content is returned unchanged.
    """
    if has_managed_marker(content):
        return content
    first, sep, rest = content.partition("\n")
    if first.strip().lower() == "@echo off" and sep:
        return first + "\n" + MARKER_BATCH_COMMENT + "\n" + rest
    return MARKER_BATCH_COMMENT + "\n" + content


# ── Seed-version stamp (init-seeded docs) ──────────────────────────────────

SEED_STAMP_TOKEN = "espalier:seed-version"
"""First-line provenance token ``espalier init`` writes ahead of every
seeded doc (``managed_inventory.get_seed_docs()``). Deliberately NOT
``espalier:managed``: a seed is operator-OWNED after it lands --
``clean-generated`` never deletes it and an operator edit is preserved --
but it is still harness-PROVENANCE content, and that second property is
what the fingerprint needs. A 464 KB ``docs/FAILURE_MODES.md`` seeded into a
three-file repo must not read as the adopter's large file, docs-heavy
profile or docs surface (DEF-410f / DEF-686). Keyed on the stamp rather
than on a path because the same path, unstamped, IS the adopter's doc."""

SEED_STAMP_RE = re.compile(
    r"^<!-- espalier:seed-version v\S+ sha256:([0-9a-f]{64}) -->\n"
)
"""Anchored at offset 0 -- the stamp is the FIRST line or it is not a stamp.
The captured sha256 is the digest of every byte BELOW the stamp line
(``seed_is_untouched`` recomputes it). Single owner; ``cli._SEED_STAMP_RE``
is an alias."""

SEED_STAMP_SCAN_BYTES = 256
"""Bytes read by ``path_has_seed_stamp``. The stamp line is ~120 bytes
(token + version + 64-hex digest + comment close); 256 leaves room for a
long version string without reading the body of a multi-hundred-KB seed."""


def _normalise_seed_text(content: str) -> str:
    """Line endings and a leading BOM are not edits.

    ``init`` writes the stamp with ``\n``; a Windows editor may resave the
    seed with ``\r\n`` and/or a UTF-8 BOM without the adopter touching a
    word. Text-mode readers (``Path.read_text``) already fold ``\r\n`` to
    ``\n``; the byte-mode peek in ``path_has_seed_stamp`` did not, so a
    CRLF-resaved seed silently re-entered the fingerprint (caught in review
    before it shipped). Every stamp reader goes through this one helper so
    the four call sites answer the same question the same way.
    """
    if content.startswith("\ufeff"):
        content = content[1:]
    return content.replace("\r\n", "\n")


def seed_stamp_digest(content: str) -> str | None:
    """The sha256 recorded in ``content``'s first-line seed stamp, else None."""
    m = SEED_STAMP_RE.match(_normalise_seed_text(content))
    return m.group(1) if m else None


def has_seed_stamp(content: str) -> bool:
    """True if ``content`` opens with a seed-version stamp line."""
    return SEED_STAMP_RE.match(_normalise_seed_text(content)) is not None


def seed_is_untouched(content: str) -> bool:
    """True if ``content`` carries a seed stamp AND the bytes below it still
    hash to the recorded digest -- the operator has not edited the seed.

    An unstamped doc returns False (cannot be proven untouched), as does a
    stamped doc with any post-stamp change. ``doctor`` uses this to tell an
    untouched seeded ``docs/CONVENTIONS.md`` stub from a populated one
    (DEF-687): the stub ships more content lines than the old line-count
    floor, so line-counting alone read every fresh install as grounded.
    """
    import hashlib

    content = _normalise_seed_text(content)
    m = SEED_STAMP_RE.match(content)
    if m is None:
        return False
    return hashlib.sha256(content[m.end():].encode("utf-8")).hexdigest() == m.group(1)


def path_has_seed_stamp(path: Path) -> bool:
    """True if the regular file at ``path`` opens with a seed-version stamp.

    PRESENCE, not hash, on purpose: a seed the adopter has edited is still
    harness-provenance for fingerprint purposes (their edits do not make the
    other 460 KB theirs). The one way to reclaim a seed as adopter content is
    to delete the stamp line; ``cli._count_unstamped_seed_docs`` sees that
    state and ``upgrade`` reports it. ``seed_is_untouched`` is the hash-keyed
    sibling for the question doctor asks (has anyone grounded this yet?).

    Reads only ``SEED_STAMP_SCAN_BYTES`` so the fingerprint walk can ask this
    of every Markdown file without paying for the seeds it is about to skip.
    A missing path, a non-regular file, or an unreadable file returns False
    (an unreadable doc is not proven to be ours). Replacement decoding so a
    partially-binary file cannot raise.
    """
    if not path.exists() or not path.is_file():
        return False
    try:
        with path.open("rb") as fh:
            head = fh.read(SEED_STAMP_SCAN_BYTES)
    except OSError:
        return False
    return has_seed_stamp(head.decode("utf-8", errors="replace"))
