"""Self-host check — verify the harness's own CC surface is healthy."""
from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from espalier import surface_contract
from espalier.analyze import fingerprint_repo
from espalier.proofs import first_error_detail, run_cc_surface_gate


def run_self_host_check(
    repo_root: Path,
    *,
    mode: str = "auto",
) -> dict[str, Any]:
    """Prove the harness's own CC surface is healthy.

    ``mode`` controls which gate runs.

    - ``mode="auto"`` (default): detect mode from disk via
      :func:`espalier.repo_mode.detect_repo_mode` and dispatch
      accordingly.
    - ``mode="source-checkout"``: prove the committed surface is
      coherent (every required file exists, every entry in
      ``cc/PACK_MANIFEST.txt`` exists and classifies public). Do
      NOT require ``.claude/settings.json``, ``.espalier/integrity.json``,
      or any ``reports/*.json`` — those are generated by ``init``,
      not committed.
    - ``mode="initialized"``: strict gate via
      :func:`espalier.proofs.run_cc_surface_gate`. Requires
      generated runtime files.
    """
    from espalier.repo_mode import (
        REPO_MODE_INITIALIZED_CONSUMER,
        REPO_MODE_INITIALIZED_SELF_HOST,
        REPO_MODE_SOURCE_CHECKOUT,
        resolve_mode,
    )

    from espalier import surface_contract

    repo_root = repo_root.resolve()
    resolved_mode = resolve_mode(mode, repo_root)
    fp = fingerprint_repo(repo_root)

    base_report = {
        "repo_root": str(repo_root),
        "mode_requested": mode,
        "mode_resolved": resolved_mode,
        # Whether the tree IS this engine's own source repo -- the fact the
        # gate's name is read from (``_gate_label``), recorded by the producer
        # so no consumer reads the disk again to spell a label. The mode is
        # not that fact: an adopter who commits their surface and clones fresh
        # lands in ``source_checkout`` too (DEF-785).
        "self_host_repo": bool(surface_contract.is_self_host_repo(repo_root)),
        # Emit the distinct profiles field, not raw languages — the key is
        # named "profiles" so it must carry fp.profiles
        # (e.g. python_library/docs_heavy), not language tags.
        "profiles": list(fp.profiles),
    }

    if resolved_mode == REPO_MODE_SOURCE_CHECKOUT:
        source_gate = _run_source_checkout_gate(repo_root)
        return {
            **base_report,
            "surface_gate_status": source_gate["status"],
            "gate_details": source_gate,
        }

    # Initialized modes (self-host or consumer) — strict runtime gate
    if resolved_mode in (
        REPO_MODE_INITIALIZED_SELF_HOST,
        REPO_MODE_INITIALIZED_CONSUMER,
    ):
        gate = run_cc_surface_gate(repo_root)
        details: dict[str, Any] = dict(gate)
        # The gate reports findings, not a sentence. On a FAILING gate its
        # first error-level finding is the reason a failure hands on, so the
        # status-only form of gate_failure_reason is no longer what an adopter
        # reads (DEF-785). A passing gate carries no reason: an error-level
        # finding beside a pass would otherwise be forwarded as one.
        first_error = first_error_detail(gate)
        gate_status = str(gate.get("status", "unknown"))
        if (
            first_error
            and gate_status not in GATE_STATUS_NON_FAILURES
            and not details.get("primary_reason")
        ):
            details["primary_reason"] = first_error
        return {
            **base_report,
            "surface_gate_status": str(gate.get("status", "unknown")),
            "gate_details": details,
        }

    # Uninitialized — return a structured first-run hint, not a failure
    return {
        **base_report,
        "surface_gate_status": "uninitialized",
        "gate_details": {
            "status": "uninitialized",
            "primary_reason": (
                "repo has not been initialized for Espalier-Harness; "
                "run `espalier init .` first"
            ),
        },
    }


GATE_STATUS_NON_FAILURES: frozenset[str] = frozenset({
    "pass",                    # the gate ran and passed
    "uninitialized",           # deliberate structured first-run hint (see above)
    "skipped_release_export",  # the gate correctly stood down on an export
    "skipped",                 # the caller elected not to run it (doctor)
})
"""Statuses that must NOT be reported as a failure.

Single owner. ``surface_gate_status`` is four-valued and was read by four
independently-written accept-sets -- ``cli.cmd_self_host`` and ``main`` below
each spelled out the same correct three-status rule, ``doctor`` accepted
``{pass, skipped}`` and ``pre_release`` accepted ``{pass}`` alone. The narrowest
of those turned a first-run hint into "self-host check failed" on an
uninitialized tree. One policy, one place.

⚠ ONE READER CANNOT SHARE THIS, BY ARCHITECTURE. ``tools/cc/session_resume.py``
reads the same field (``surface_gate_status.lower() != "pass"``) and ``tools/cc/``
has zero espalier imports by contract, so it can neither import this set nor be
seen by the guard that pins it (``test_the_accept_set_has_exactly_one_home``
scans ``espalier/*.py``). It is not a live divergence today -- ``run_cc_surface_gate``
emits only ``pass``/``fail`` -- but the day this gate returns any other
non-failure there, session_resume will report ``Surface: DEGRADED`` for a
stand-down. Update it by hand if this set grows.
"""


def gate_failure_reason(report: Mapping[str, Any]) -> str | None:
    """``None`` when ``report`` is not a failure, else an ACTIONABLE sentence.

    Two jobs, and the FIRST is the load-bearing one: classify. A status outside
    ``GATE_STATUS_NON_FAILURES`` is a failure and nothing else is -- which is
    what stops an uninitialized tree being reported as "self-host check failed".
    That tree's actionable sentence (``gate_details.primary_reason``, "run
    `espalier init .` first") reaches the operator through the caller's report
    block, not through this return value, because it is not a failure.

    Second, it forwards ``primary_reason`` when a FAILING report carries one.
    The ``uninitialized`` branch above always did; since 2026-09-12 the
    initialized branch populates it from the gate's first error-level finding
    (DEF-785), so a real failure names the finding, not only the status.
    ``_run_source_checkout_gate`` still returns ``findings`` alone, and that
    failure keeps the status-only form.

    The label is the gate's name on the tree it ran on (``_gate_label``): on
    any tree that is not this engine's own source repo, the harness's managed
    surface, because "self-host" is a check name from this engine's own tree.
    """
    status = str(report.get("surface_gate_status", "unknown"))
    if status in GATE_STATUS_NON_FAILURES:
        return None
    details = report.get("gate_details")
    reason = ""
    if isinstance(details, Mapping):
        reason = str(details.get("primary_reason") or "").strip()
    label = _gate_label(report)
    return f"{label} ({status}): {reason}" if reason else f"{label}: {status}"


def _gate_label(report: Mapping[str, Any]) -> str:
    """The gate, named by what it verifies on the tree it ran on.

    On any tree that is not this engine's own source repo that is the
    harness's MANAGED SURFACE. "self-host surface gate" is the same check's
    name on the Espalier-Harness tree, and it reached adopters on every
    half-installed consumer tree until 2026-09-12 (DEF-785: ``doctor`` listed
    it beside the presence failure and counted two errors for one). The fact
    is the producer's ``self_host_repo`` flag, not the mode: an adopter's
    fresh clone of a repo that commits its surface is a ``source_checkout``
    too. A report without the flag (a hand-built one) keeps the self-host
    name, as every existing pin expects.
    """
    if report.get("self_host_repo") is False:
        return "managed surface gate"
    return "self-host surface gate"


def _run_source_checkout_gate(repo_root: Path) -> dict[str, Any]:
    """Source-only gate: every required file exists, every manifest
    entry exists and is public.

    Does not require init-generated runtime files.

    Stands down on a *source-release export*. An export ships the whole
    self-host CODE layout but prunes the tracked-but-``export-ignore``'d dev
    CONTENT (``ESPALIER_MEMORY.md`` and the other ``.gitattributes`` sentinels), so
    asserting this dev-consistency gate against it is a category error that
    emits false ``manifest entry missing from source`` findings — the trap the
    release matrix's stage-02 ``self-host --mode source-checkout`` hit on the
    extracted archive. ``is_release_export`` is the correct discriminator
    (layout AND pruned content), not ``is_self_host_repo`` (layout alone, True
    for an export too); it is conservative (positive-confirmation only), so any
    uncertainty runs the full gate — a loud failure on a real export beats a
    silent skip on a dev tree.
    """
    from espalier import surface_contract

    if surface_contract.is_release_export(repo_root):
        return {
            "status": "skipped_release_export",
            "mode": "source_checkout",
            "findings": [],
            "checks_run": [],
            "note": (
                "repo_root is a source-release export (self-host layout with "
                "dev content pruned); the source-checkout dev-consistency gate "
                "is not applicable"
            ),
        }

    findings: list[str] = []

    # 1. Every required init file is present in source
    for rel in surface_contract.get_required_init_files():
        if not (repo_root / rel).exists():
            findings.append(f"required init file missing in source: {rel}")

    # 2. Every entry in cc/PACK_MANIFEST.txt exists and classifies public
    manifest_path = repo_root / "cc" / "PACK_MANIFEST.txt"
    if not manifest_path.exists():
        findings.append("cc/PACK_MANIFEST.txt is missing")
    else:
        # Names, read with a replacement character: a code-page re-save of
        # the manifest reports its entries missing instead of crashing doctor
        # (DEF-829).
        text = manifest_path.read_text(encoding="utf-8", errors="replace")
        for line in text.splitlines():
            entry = line.strip()
            if not entry or entry.startswith("#"):
                continue
            if not (repo_root / entry).exists():
                findings.append(f"manifest entry missing from source: {entry}")
                continue
            bucket = surface_contract.classify_release_path(entry)
            if bucket != "public":
                findings.append(
                    f"manifest entry classified {bucket} (not public): {entry}"
                )

    status = "pass" if not findings else "fail"
    return {
        "status": status,
        "mode": "source_checkout",
        "findings": findings,
        "checks_run": [
            "required_init_files_present",
            "manifest_entries_exist",
            "manifest_entries_classify_public",
        ],
    }


def main(argv: list[str] | None = None) -> int:
    """Module-level entry point — mirrors ``espalier self-host`` CLI behavior.

    Accepts ``--mode`` so direct module invocation
    (``python -m espalier.self_hosting``) and the package CLI
    (``espalier self-host``) behave identically. Both return exit 0 for
    the structured-hint ``uninitialized`` status — failures are reserved
    for genuine gate failures.
    """
    parser = argparse.ArgumentParser(description="Run Espalier-Harness surface health check")
    parser.add_argument("repo_root", type=Path)
    parser.add_argument(
        "--mode", choices=("auto", "source-checkout", "initialized"),
        default="auto",
        help=(
            "explicit repo-mode override. 'source-checkout' proves the "
            "committed surface only — does not require init-generated "
            "runtime files. 'initialized' runs the full strict gate. "
            "'auto' (default) detects mode from disk state."
        ),
    )
    args = parser.parse_args(argv)
    # The same question `espalier self-host` asks in `cli._resolve_repo_arg`,
    # with the same exit: this entry point resolves its own argument, and
    # the walk below crashed on a `.claude` it could not search on CPython
    # 3.10-3.13 (DEF-763, found by the lane's code review).
    unreadable = surface_contract.unreadable_harness_root(args.repo_root)
    if unreadable is not None:
        print(
            f"error: {surface_contract.unreadable_root_sentence(unreadable)}",
            file=sys.stderr,
        )
        return 2
    report = run_self_host_check(args.repo_root, mode=args.mode)
    print(json.dumps(report, indent=2))
    # One accept-set, shared with cmd_self_host / doctor / pre_release: a
    # stand-down ('skipped_release_export') and a first-run hint
    # ('uninitialized') are successes, not failures.
    return 0 if gate_failure_reason(report) is None else 1


if __name__ == "__main__":
    raise SystemExit(main())
